---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/10 16:50
---

---@class lcrypt
local lcrypt = {}

---@param s string
---@return string
function lcrypt.sha1(s)
end

---@param s string
---@return string
function lcrypt.md5(s)
end

---@param s string
---@return string
function lcrypt.base64_encode(s)
end

---@param s string
---@return string
function lcrypt.base64_decode(s)
end

---@param key string
---@param s string
---@return string
function lcrypt.aes_encrypt(key,s)
end

---@param key string
---@param s string
---@return string
function lcrypt.aes_decrypt(key,s)
end

---@param s string
---@return string
function lcrypt.rand_bytes(length)
end

---@param user string
---@param password string
---@return string salt
---@return string verifier
function lcrypt.srp_create_verifier(user,password)
end

---@param verifier string
---@return string privKey
---@return string pubKey
function lcrypt.srp_create_key_server(verifier)
end

---@return string privKey
---@return string pubKey
function lcrypt.srp_create_key_client()
end

---@param verifier string
---@param serverPrivKey string
---@param serverPubKey string
---@param clientPubKey string
---@return string sessionKey
function lcrypt.srp_create_session_key_server(verifier,serverPrivKey,serverPubKey,clientPubKey)
end

---@param salt string
---@param clientPrivKey string
---@param clientPubKey string
---@param serverPubKey string
---@return string sessionKey
function lcrypt.srp_create_session_key_client(salt,clientPrivKey,clientPubKey,serverPubKey)
end