---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/2/26 16:44
---


---@class lfixed
local lfixed = {}

---@param value number | integer | fixed
---@return fixed
function lfixed.new(value)
end

---@class fixed
local fixed = {}

---@return number
function fixed:toNumber()
end

---@return integer
function fixed:toInteger()
end

---@return string
function fixed:toString()
end

---@param value number | integer | fixed  @[optional]
---@return fixed
function fixed:reset(value)
end

--[[ meta method
	__add
	__sub
	__mul
	__div
	__eq
	__lt
	__le
	__tostring
]]
