---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 15:54
---

---@class lhparser
local lhparser = {}

---@param url string
---@param isConnect boolean
---@return lhparser_parse_url
function lhparser.parse_url(url,isConnect)
end

---@param callbacks lhparser_callback
---@return lhparser_context
function lhparser.request(callbacks)
end

---@param callbacks lhparser_callback
---@return lhparser_context
function lhparser.response(callbacks)
end


---@class lhparser_parse_url
---@field public schema string
---@field public host string
---@field public path string
---@field public query string
---@field public fragment string
---@field public userinfo string
local lhparser_parse_url = {}

---@class lhparser_context
local lhparser_context = {}

---@return string
function lhparser_context:method()
end

---@return integer http major version
---@return integer http minor version
function lhparser_context:version()
end

---@return integer
function lhparser_context:status_code()
end

---@return string errno
---@return string errno name
---@return string errno desc
function lhparser_context:error()
end

---@return boolean
function lhparser_context:keep_alive()
end

---@return boolean
function lhparser_context:upgrade()
end

---@return integer parser length
function lhparser_context:execute()
end

---@param callbacks lhparser_callback
function lhparser_context:reset(callbacks)
end

---@class lhparser_callback
---@field public on_message_begin function
---@field public on_url function
---@field public on_status function
---@field public on_header function
---@field public on_headers_complete function
---@field public on_body function
---@field public on_message_complete function
---@field public on_chunk_header function
---@field public on_chunk_complete function
local lhparser_callback = {}
