---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 16:45
---

---@class ljson
local ljson = {}

---@param s string | table | number | integer | boolean
---@return string json string
function ljson.encode(s)
end

---@param s string
---@param length intgeter @[optional]
---@return string | table | number | integer | boolean
function ljson.decode(s,length)
end
