---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 16:45
---

---@class lmsgpack
local lmsgpack = {}

---@param s string | table | number | integer | boolean
---@return string
function lmsgpack.encode(s)
end

---@param s string
---@param length integer @[optional]
---@return string | table | number | integer | boolean
function lmsgpack.decode(s,length)
end

