---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 16:45
---


---@class lpbc
local lpbc = {}

---@param s string
function lpbc.init(s)
end

function lpbc.cleanup()
end

---@param filename string
---@return boolean
function lpbc.importer(filename)
end

---@param name string
---@param s string
---@param length integer @[optional]
---@return table<string,any>
function lpbc.decode(name,s,length)
end

---@param name string
---@param proto table<string,any>
---@return userdata data 
---@return integer length
function lpbc.encode(name,proto)
end

---@param name string
---@param proto table<string,any>
---@return string
function lpbc.encode_string(name,proto)
end