---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/10 16:48
---


---@class lproject
local lproject = {}

---@return boolean
function lproject.startup()
end

---@param callback function
function lproject.set_beginplay_callback(callback)
end

---@param callback function
function lproject.set_endplay_callback(callback)
end

---@param callback function
function lproject.set_tick_callback(callback)
end

---@return string
function lproject.get_content_dir()
end

---@return string
function lproject.get_app_external_dir()
end

---@return string
function lproject.get_app_sandboxes_dir()
end