---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 17:07
---


---@class ltw2
---@field public core ltw2_core
---@field public event ltw2_event
---@field public ringbuf ltw2_ringbuf
local ltw2 = {}


---@class ltw2_core
local ltw2_core = {}

---@param cbuffer userdata
---@param length integer
---@return string
function ltw2_core.cbuffer_to_string()
end

---@return integer
function ltw2_core.clock_monotonic()
end

---@return integer
function ltw2_core.clock_realtime()
end

---@param duration integer
function ltw2_core.sleep_for(duration)
end

---@param capacity integer
---@return ltw2_ringbuf
function ltw2_core.ringbuf_new(capacity)
end

---@class ltw2_ringbuf
local ltw2_ringbuf = {}

function ltw2_ringbuf:reset()
end

---@return integer capacity
function ltw2_ringbuf:capacity()
end

---@param length integer
---@return string read data
---@return integer read length
function ltw2_ringbuf:read(length)
end

---@param length integer
---@return string read data
---@return integer read length
function ltw2_ringbuf:read_skip(length)
end

---@return string
function ltw2_ringbuf:tostring()
end

---@param length integer
---@return string read data
---@return integer readable
function ltw2_ringbuf:readline_eol(length)
end

---@param length integer
---@return string read data
---@return integer readable
function ltw2_ringbuf:readline_crlf(length)
end

---@return string read data
function ltw2_ringbuf:readall()
end

---@param s string
---@param length integer @[optional]
---@return integer write length
function ltw2_ringbuf:write(s,length)
end

---@return integer readable
function ltw2_ringbuf:size()
end

---@class ltw2_event
local ltw2_event = {}

---@param concurrentThreads integer
---@return boolean
function ltw2_event.start(concurrentThreads)
end

---@return boolean
function ltw2_event.stop()
end

---@return boolean
function ltw2_event.run()
end

---@return ltw2_event_timer_watcher
function ltw2_event.timer_watcher_new()
end

---@return ltw2_event_connection
function ltw2_event.connection_new()
end

---@class ltw2_event_timer_watcher
local ltw2_event_timer_watcher = {}

---@param intervalMs integer
---@param bOnce integer @[optional]
---@param callback function
---@return boolean
function ltw2_event_timer_watcher:start(intervalMs,bOnce,callback)
end

function ltw2_event_timer_watcher:stop()
end

---@class ltw2_event_connection
local ltw2_event_connection = {}

---@param bStream integer Tcp or Udp
---@param address string
---@param callback function callback(bSucc)
---@return boolean
function ltw2_event_connection:connect(bStream,address,callback)
end

---@param callback function
function ltw2_event_connection:set_disconnect_callback(callback)
end

---@param callback function callback(data)
function ltw2_event_connection:set_receive_callback(callback)
end

---@param callback function
function ltw2_event_connection:set_close_callback(callback)
end

---@param bKeepAlive integer
---@param bTcpNoDelay integer
---@return boolean
function ltw2_event_connection:bind(bKeepAlive,bTcpNoDelay)
end

---@param bForce boolean @[optional]
function ltw2_event_connection:close(bForce)
end

---@param s string
---@param length integer @[optional]
---@return integer send length
function ltw2_event_connection:send(s,length)
end
