---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 16:49
---

---@class lwsproto
local lwsproto = {}

---@param opcode integer
---@param maskingKey integer
---@param s string
---@param length integer @[optional]
---@return any string
function lwsproto.write(opcode,maskingKey,s,length)
end
---@param s string
---@param length integer @[optional]
---@return integer opcode
---@return string
function lwsproto.read(s,length)
end
