---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 16:49
---

---@class lwsproto
local lwsproto = {}

---@param opcode intgeter
---@param maskingKey intgeter
---@param s string
---@param length intgeter @[optional]
---@return any string
function lwsproto.write(opcode,maskingKey,s,length)
end
---@param s string
---@param length intgeter @[optional]
---@return intgeter opcode
---@return string
function lwsproto.read(s,length)
end
