---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 17:06
---

---@class lxml
local lxml = {}

---@param s string
---@param length intgeter @[optional]
---@return table
function lxml.parse(s)
end


