---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/3/03
---

local LuaHelper = require("Utility.LuaHelper")
local Fix = require("lfixed")
local Buff = require("GamePlay.Combat.GameLogic.Buff")
local CombatConst = require("GamePlay.Combat.GameLogic.CombatConst")

---@class PropBuffer
local M = LuaHelper.LuaClass("GamePlay.Combat.GameLogic.Buff")

function M:__OnNew(buffData)
	-- 调用基类构造函数
	M.super:__OnNew(buffData)
	-- 设置为属性Buff类型
	self.category = Buff.BuffCategory.Stat
	-- 保存属性参数列表（格式：{"属性ID:固定值:百分比", ...}）
	self.param = buffData.param or {}
end

--- 修改属性修正值
--- 注意：此函数必须在 SetTarget 之后调用，因为需要访问 target 的属性
function M:Modify()
	if not self.param or #self.param == 0 then
		return
	end
	
	for _, propStr in pairs(self.param) do
		-- 解析参数字符串（格式："属性ID:固定值:百分比"）
		local parts = {}
		for part in string.gmatch(propStr, "[^:]+") do
			table.insert(parts, part)
		end
		
		local propTypeId = tonumber(parts[1]) or 0
		local propValue = Fix.new(tonumber(parts[2]) or 0)
		local propPercent = Fix.new(tonumber(parts[3]) or 0)
		
		-- 获取属性名
		local propName = CombatConst.PropTypeToName[propTypeId]
		if not propName then
			print("[PropBuff] Warning: Unknown property type ID:", propTypeId)
			goto continue
		end
		
		-- 设置固定值修正
		if propValue ~= CombatConst.zero then
			self.statModifier[propName] = propValue
		end
		
		-- 设置百分比修正（如果有）
		if propPercent ~= CombatConst.zero then
			local percentPropName = propName .. "Percent"
			self.statModifier[percentPropName] = propPercent
		end
		
		::continue::
	end
end

--- 设置目标和来源（重写基类方法，在设置后调用 Modify）
---@param source CombatEntity 来源实体
---@param target CombatEntity 目标实体
function M:SetTarget(source, target)
	M.super.SetTarget(self, source, target)
	-- 在 target 设置后调用 Modify
	self:Modify()
end

--- 应用治疗效果（即时Buff，添加时立即执行）
---@param eventData table 事件数据
function M:ApplyEffect(eventData)
	-- PropBuff 是属性Buff，不需要 ApplyEffect
end

return M