---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/12 17:39
---

---@type lpbc
local lpbc = require "lpbc"
---@type JsonFile
local JsonFile = require "Utility.JsonFile"

local mapNameAndId = {}
local mapIdAndName = {}

---@class NetPack
local M = {}

function M.Init(path)
	local messageId = JsonFile.Read(path)
    for _, message in pairs(messageId.Message) do
        local name = message.name
        local id = message.id
		mapNameAndId[name] = id
		mapIdAndName[id] = name
    end
end

function M.Pack(name, proto)
	local id = mapNameAndId[name]
	if not id then
		return nil
	end
	local data = lpbc.encode_string(name,proto)
	local message = {
		code = id,
		content = data,
	}
	return lpbc.encode_string("GameBaseProtobufMessage", message)
end

function M.Unpack(data)
    local message = lpbc.decode("GameBaseProtobufMessage", data)
	if not message then
        return nil
    end
    local id = message.code
    local name = mapIdAndName[id]
    if not name then
        return nil
    end
    return name,lpbc.decode(name, message.content)
end

return M