---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/12 11:42
---
---
---

---@type lcrypt
local lcrypt = require("lcrypt")
---@type Channel
local Channel = require("Core.Channel")
---@type EventLoop
local EventLoop = require("Core.EventLoop")
---@type NetPack
local NetPack = require("Net.NetPack")
---@type ProtoDispatcher
local ProtoDispatcher = require("Core.ProtoDispatcher")
---@type EventDispatcher
local EventDispatcher = require("Core.EventDispatcher")

---@type LuaHelper
local LuaHelper = require("Utility.LuaHelper")

local Interface = require("Utility.Interface")

local CONNECTING<const> = 0
local CONNECTING_HANDSHAKE<const> = 1
local CONNECTED<const> = 2
local DISCONNECTED<const> = 3

local function SendHandShakeMsg(self, name, proto)
	local data = NetPack.Pack(name, proto)
	if not data then
		return
	end
	local length = #data
	local msg = string.pack(">I4", length) .. data	
	return self.channel:Send(msg)
end

local function SendPack(self,name,proto)
	local data = NetPack.Pack(name, proto)
	if not data then
		return
	end
	local s = lcrypt.aes_encrypt(self.key, data)
	local length = #s
	local msg = string.pack(">I4", length) .. s
	return self.channel:Send(msg)
end

local function OnMessage(self, data)
	if self.status == CONNECTED or self.status == CONNECTING_HANDSHAKE then
		self.msgCache = self.msgCache .. data
		local packLength = #self.msgCache
		if packLength < 4 then
            return
        end
		
		local length = string.unpack(">I4", self.msgCache:sub(1,4))
		if length + 4 < packLength then
			return
		end
		
		local dataMsg = self.msgCache:sub(5, length + 4)
		local packMsg = lcrypt.aes_decrypt(self.key, dataMsg)
		self.msgCache = self.msgCache:sub(length + 5)
		local name, msg = NetPack.Unpack(packMsg)
        if not name then
            return
        end
        ProtoDispatcher.DispatchMessage(name, msg)
	end
end

local function OnHandShakeMessage(self, data)
	if self.status == CONNECTING_HANDSHAKE then
		self.msgCache = self.msgCache .. data
		local packLength = #self.msgCache
		if packLength < 4 then
			return
		end

		local length = string.unpack(">I4", self.msgCache:sub(1,4))
		if length + 4 < packLength then
			return
		end

		local packMsg = self.msgCache:sub(5, length + 4)
		self.msgCache = self.msgCache:sub(length + 5)
		local name, msg = NetPack.Unpack(packMsg)
		if not name or not msg then
			return
		end
		ProtoDispatcher.DispatchMessage(name, msg)
	end
end

local function OnGCSceneInfoBuf(self,proto)
	if self.status ~= CONNECTING_HANDSHAKE then
		return
	end
	self.status = CONNECTED
	if self.heartTimeout then
		self.heartTimeout:stop()
		self.heartTimeout = nil
	end
	self.heartTimeout = EventLoop.Timeout(20000, function()
		if self.status ~= CONNECTED then
			return
		end

		local CGPingBuf = {
			timestamp = EventLoop.ClockMonotonic(),
		}
		self:Send("CGPingBuf", CGPingBuf)
	end, true)
	EventDispatcher.Dispatch("AccountLoginSuccess", self)
end

local function OnACHandShakeBuf(self,proto)
	if self.status ~= CONNECTING_HANDSHAKE then
		return
	end
	
	local CAPlayerCookieLoginBuf = {
		timestamp = EventLoop.ClockMonotonic(),
		tokenValue = self.userName,
		serverId = 1001,
		terminalInfos = { auth = "guest" } ,
	}
	SendPack(self,"CAPlayerCookieLoginBuf", CAPlayerCookieLoginBuf)
end

local function OnACPublicKeyExchangeBuf(self, proto)
    if self.status == CONNECTING_HANDSHAKE then
        local remotePubKey = proto.publicKey
		local localPrivKey, localPubKey = lcrypt.srp_create_key_client()
		local sessionKey = lcrypt.srp_create_session_key_client(self.userName,self.password,self.salt,localPrivKey,localPubKey,remotePubKey)
		local key = lcrypt.sha256(sessionKey)
		self.key = string.sub(key, 1, 16)
		self.password = nil
		self.salt = nil
		local handler = LuaHelper.Handler(self, OnMessage)
		self.channel:SetMessageCallback(handler)
		
		local CAPublicKeyExchangeBuf = {
            timestamp = EventLoop.ClockMonotonic(),
			publicKey = localPubKey, 
        }
        SendHandShakeMsg(self, "CAPublicKeyExchangeBuf", CAPublicKeyExchangeBuf)
    end
end

local function HandShake(self)
	self.status = CONNECTING_HANDSHAKE
	local salt,verifier = lcrypt.srp_create_verifier(self.userName,self.password)
	self.salt = salt
	local handler = LuaHelper.Handler(self, OnHandShakeMessage)
	self.channel:SetMessageCallback(handler)

	self.heartTimeout = EventLoop.Timeout(20000, function()
		self.heartTimeout = nil
		if self.status == CONNECTING_HANDSHAKE then
			if self.channel then
				self.channel:Close()
				self.channel = nil
			end
			if self.disconnectCB then
				self.disconnectCB(self)
				self.disconnectCB = nil
			end
		end
	end, false)
	local CAHandShakeBuf = {
		timestamp = EventLoop.ClockMonotonic(),
		verifier = verifier,
	}
	SendHandShakeMsg(self, "CAHandShakeBuf", CAHandShakeBuf)
end

---@class TcpClient
local M = Interface("TcpClient")

function M:__init()
	self.status = DISCONNECTED
	self.userName = ""
	self.password = ""
	self.salt = ""
	self.key = ""
	self.msgCache = ""
	self.heartTimeout = nil
	self.channel = nil
	self.disconnectCB = nil

	ProtoDispatcher.AddDispatch("ACPublicKeyExchangeBuf", self, OnACPublicKeyExchangeBuf)
	ProtoDispatcher.AddDispatch("ACHandShakeBuf", self, OnACHandShakeBuf)
	ProtoDispatcher.AddDispatch("GCSceneInfoBuf", self, OnGCSceneInfoBuf)

	
end

function M:__gc()
	ProtoDispatcher.RemoveDispatch("ACPublicKeyExchangeBuf", self)
	ProtoDispatcher.RemoveDispatch("ACHandShakeBuf", self)
	ProtoDispatcher.RemoveDispatch("GCSceneInfoBuf", self)
	self:Close()
end

---@param func function(self:TcpClient)
function M:SetDisconnectCallback(func)
	self.disconnectCB = func
end

---@param user string
---@param addr string
function M:Connect(userName,password,address)
	self.status = CONNECTING
	self.msgCache = ""
	
	local channel = Channel.Connect(address,1000, true, function(bSucc)
		if bSucc then
			if self.channel:Bind(true, false) then
				self.userName = userName
				self.password = password
				HandShake(self)
				return
			end
		end
		if self.disconnectCB then
			self.disconnectCB(self)
			self.disconnectCB = nil
		end
	end)
	
	channel:SetDisconnectCallback(function()
		if self.disconnectCB then
			self.disconnectCB(self)
			self.disconnectCB = nil
		end
    end)
	
	self.channel = channel
end

function M:GetStatus()
    return self.status
end

function M:Send(name, proto)
	if self.status ~= CONNECTED then
        return
    end
	return SendPack(self,name, proto)
end

---@param timeoutMs integer
function M:Close(timeoutMs)
    if self.channel then
        self.channel:Close(timeoutMs)
		self.channel = nil
    end
	self.userName = ""
	self.password = ""
	self.salt = ""
	self.key = ""
	self.msgCache = ""
	if self.heartTimeout then
		self.heartTimeout:stop()
		self.heartTimeout = nil
	end
	self.status = DISCONNECTED
end

return M