---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/30 17:54
---

local LuaHelper = require("Utility.LuaHelper")
local UIManager = require("UI.UIManager")
local UEHelper = require("Core.UEHelper")

---@class DevelopMainController : UIControllerBase
local M = LuaHelper.LuaClass("UI.UIControllerBase")

function M:__OnNew(name, view, model)
	self.Super.__OnNew(self, name, view, model)
	self.view:SubscribeEvent("OnTestClick", self.OnTestClick, self)
	self.view:SubscribeEvent("OnCustomCharacterClick", self.OnCustomCharacterClick, self)
	self.view:SubscribeEvent("OnHomeClick", self.OnHomeClick, self)
	self.view:SubscribeEvent("OnCombatClick", self.OnCombatClick, self)
end

function M:OnTestClick()
	UIManager.State_Open("TestMain")
	print("OnTestClick")
end

function M:OnCustomCharacterClick()
	print("OnCustomCharacterClick")
end

function M:OnHomeClick()
	print("OnHomeClick")
	UE.UGameplayStatics.OpenLevel(UEHelper.GetGameInstance(),"/Game/Development/Maps/Home/l_HomeEntry")
end

function M:OnCombatClick()
	print("OnCombatClick")
	UE.UGameplayStatics.OpenLevel(UEHelper.GetGameInstance(),"/Game/Development/Maps/Combat/l_CombatEntry")
end

return M