
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---

local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")

---@class BattleLog
local M = LuaHelper.LuaClass()

function M:__OnNew()
    self.roundLogs = {}
    self.currentRoundLog = nil
    self.currentRoundIndex = 0
end

--- 开始新回合
---@param roundIndex number 回合索引
function M:StartRound(roundIndex)
    self.currentRoundIndex = roundIndex
    self.currentRoundLog = {
        RoundIndex = roundIndex,
		ActionValue = 0,
        Actions = {}
    }
    table.insert(self.roundLogs, self.currentRoundLog)
end
--
function M:LogActionValue(actionValue)
    self.currentRoundLog.ActionValue = actionValue
end

--- 记录技能行动
---@param attackerId number 攻击者ID
---@param skillId number 技能ID
---@param targetIds table 目标ID列表
---@param damages table 伤害列表
---@param weakness table 弱点列表
function M:LogSkillAction(attackerId, skillId, targetIds, damages, weakness)
    if not self.currentRoundLog then
        return
    end
    
    local action = {
        ActionType = CombatState.ActionType.Skill,
        AttackerId = attackerId,
        SkillId = skillId,
        TargetIds = targetIds or {},
        Damages = damages or {},
        Weakness = weakness or {}
    }
    
    table.insert(self.currentRoundLog.Actions, action)
end

--- 记录Buff行动
---@param targetId number 目标ID
---@param buffId number BuffID
---@param effectType string 效果类型
---@param effectValue number 效果值
function M:LogBuffAction(targetId, buffId, effectType, effectValue)
    if not self.currentRoundLog then
        return
    end
    
    local action = {
        ActionType = CombatState.ActionType.Buff,
        TargetId = targetId,
        BuffId = buffId,
        EffectType = effectType,
        EffectValue = effectValue
    }
    
    table.insert(self.currentRoundLog.Actions, action)
end

--- 结束当前回合
function M:EndRound()
    self.currentRoundLog = nil
end

--- 获取当前回合日志
---@return table
function M:GetCurrentRoundLog()
    return self.currentRoundLog
end

--- 获取所有回合日志
---@return table
function M:GetAllRoundLogs()
    return self.roundLogs
end

--- 获取指定回合日志
---@param roundIndex number 回合索引
---@return table|nil
function M:GetRoundLog(roundIndex)
    for _, log in ipairs(self.roundLogs) do
        if log.RoundIndex == roundIndex then
            return log
        end
    end
    return nil
end

--- 输出当前回合日志（JSON格式）
function M:PrintCurrentRoundLog()
    if not self.currentRoundLog then
        return
    end
    
    local json = self:TableToJson(self.currentRoundLog)
    print("[BattleLog] Round", self.currentRoundIndex, ":")
    print(json)
end

--- 输出所有回合日志
function M:PrintAllRoundLogs()
    print("[BattleLog] All Rounds:")
    for _, log in ipairs(self.roundLogs) do
        local json = self:TableToJson(log)
        print(json)
    end
end

--- 简单的Table转JSON函数
---@param tbl table
---@return string
function M:TableToJson(tbl)
    if type(tbl) ~= "table" then
        return tostring(tbl)
    end
    
    local result = "{"
    local first = true
    
    for key, value in pairs(tbl) do
        if not first then
            result = result .. ","
        end
        first = false
        
        if type(key) == "string" then
            result = result .. '"' .. key .. '":'
        else
            result = result .. key .. ":"
        end
        
        if type(value) == "table" then
            result = result .. self:TableToJson(value)
        elseif type(value) == "string" then
            result = result .. '"' .. value .. '"'
        elseif type(value) == "number" then
            result = result .. tostring(value)
        elseif type(value) == "boolean" then
            result = result .. (value and "true" or "false")
        else
            result = result .. '"' .. tostring(value) .. '"'
        end
    end
    
    result = result .. "}"
    return result
end

--- 清空所有日志
function M:Clear()
    self.roundLogs = {}
    self.currentRoundLog = nil
    self.currentRoundIndex = 0
end

return M
