---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/28
---

local LuaHelper = require("Utility.LuaHelper")
local HealBuffer = require("GamePlay.Combat.GameLogic.Buff.HealBuff")

---@class BufferFactory
local M = LuaHelper.LuaClass()

function M:__OnNew()
	self.buffMap = {}
	-- 注册Buff类型
	self:RegisterBuff(1, HealBuffer)

	-- 可以继续添加更多Buff类型
end

--- 创建Buff实例
---@param buffData table Buff数据
---@return Buff|nil
function M:Make(buffData)
	if not buffData or not buffData.id then
		print("[BufferFactory] Error: buffData or buffData.id is nil")
		return nil
	end

	local buffClass = self.buffMap[buffData.id]
	if not buffClass then
		print("[BufferFactory] Error: Unknown buff id:", buffData.id)
		return nil
	end

	local buff = buffClass:New(buffData)
	print("[BufferFactory] Created buff:", buffData.id, buff.name)
	return buff
end

--- 注册新的Buff类型
---@param buffId number BuffID
---@param buffClass table Buff类
function M:RegisterBuff(buffId, buffClass)
	self.buffMap[buffId] = buffClass
	print("[BufferFactory] Registered buff:", buffId)
end

--- 获取已注册的Buff类型数量
---@return number
function M:GetRegisteredBuffCount()
	local count = 0
	for _ in pairs(self.buffMap) do
		count = count + 1
	end
	return count
end

return M