
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/28
---

local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")
local Fix = require("lfixed")

---@class Buff
local M = LuaHelper.LuaClass()


function M:__OnNew(buffData)
    self.id = buffData.id or 0
    self.name = buffData.name or "UnknownBuff"
    self.buffType = buffData.buffType or CombatState.ActionType.Buff
	self.targetType = buffData.targetType
    self.duration = buffData.duration or 1
    self.maxDuration = buffData.duration or 1
    self.stackCount = buffData.stackCount or 1
    self.maxStackCount = buffData.maxStackCount or 1
    
    -- 效果类型
    self.effectType = buffData.effectType or "none" -- none, damage, heal, buff_stat, debuff_stat
    self.effectValue = buffData.effectValue or Fix.new(0)
    
    -- 属性修改
    self.statModifier = buffData.statModifier or {}
    self.statModifier.hp = buffData.statModifier and buffData.statModifier.hp or Fix.new(0)
    self.statModifier.attack = buffData.statModifier and buffData.statModifier.attack or Fix.new(0)
    self.statModifier.defense = buffData.statModifier and buffData.statModifier.defense or Fix.new(0)
    self.statModifier.speed = buffData.statModifier and buffData.statModifier.speed or Fix.new(0)
    
    self.description = buffData.description or ""
end

--- 应用Buff效果
---@param target CombatEntity 目标实体
function M:ApplyEffect(target)
	
	
end

--- 移除Buff效果
---@param target CombatEntity 目标实体
function M:RemoveEffect(target)
    -- 如果是永久属性修改，需要在这里移除
    -- 当前实现是临时属性修改，不需要额外处理
end

--- 减少持续时间
---@return boolean 是否过期
function M:DecrementDuration()
    self.duration = self.duration - 1
    return self.duration <= 0
end

--- 增加层数
function M:AddStack()
    if self.stackCount < self.maxStackCount then
        self.stackCount = self.stackCount + 1
    end
end

--- 减少层数
function M:RemoveStack()
    self.stackCount = self.stackCount - 1
    if self.stackCount < 0 then
        self.stackCount = 0
    end
    return self.stackCount <= 0
end

--- 获取属性修正值
---@param statName string 属性名称
---@return fixed
function M:GetStatModifier(statName)
    if self.statModifier[statName] then
        return self.statModifier[statName] * Fix.new(self.stackCount)
    end
    return Fix.new(0)
end

--- 检查Buff是否过期
---@return boolean
function M:IsExpired()
    return self.duration <= 0
end

return M
