---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/2/25 17:03
---

local RandomGenerator = require("Core.RandomGenerator")

---@class CombatSystem
local M = {}

---@type RandomGenerator
local randomGenerator

local playerObjs = {}
local enemyObjs = {}

function M.Initialize()
end

function M.Deinitialize()
end

function M.RegisterPlayerObj(id,level,...)
	--该函数用于注册玩家对象
end

function M.RegisterEnemyObj(id,level,...)
	--该函数用于注册敌人对象
end

function M.BeginPlay(randomSeed)
	-- 初始化随机数生成器
	randomGenerator = RandomGenerator(randomSeed)
	--该函数用于开始战斗
end

function M.EndPlay()
	--该函数用于结束战斗
	playerObjs = {}
    enemyObjs = {}
	randomGenerator = nil
end

function M.Random()
	return randomGenerator:Next()
end

function M.RandomFloat()
    return randomGenerator:NextFloat()
end

function M.RandomFixed()
    return randomGenerator:NextFixed()
end

function M.RandomRange(min, max)
    return randomGenerator:NextRange(min, max)
end

function M.RandomRangeFixed(min, max)
    return randomGenerator:NextRangeFixed(min, max)
end

function M.RandomRangeFloat(min, max)
    return randomGenerator:NextRangeFloat(min, max)
end

function M.Choice(array)
    return randomGenerator:Choice(array)
end

return M