---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---


local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")
local CombatProp = require("GamePlay.Combat.GameLogic.CombatProp")
local CombatConst = require("GamePlay.Combat.GameLogic.CombatConst")

---@class CombatEntity
local M = LuaHelper.LuaClass()

function M:__OnNew(manager, id, position, entityType, prop)
	self.id = id
	self.combatManager = manager
	self.entityType = entityType or CombatState.EntityType.Player
	self.baseProp = CombatProp:New(prop or {})
	self.extendProp = CombatProp:New({})
	self.prop = CombatProp:New({})
	self.position = position or 0
	self.buffs = {}
	self.skills = {}
	self.position = prop.position or 0
	self.name = prop.name or ("Entity_" .. id)
end

--- 判断是否存活
---@return boolean
function M:IsAlive()
	return not self.prop.isDead
end
--- 获取战斗管理器
---@return CombatManager
function M:BattleManager()
	return self.combatManager
end

function M:CalcProp()
	self.prop = self.baseProp:Clone()

	self.prop.maxHp = self.baseProp.maxHp + self.extendProp.maxHp
	self.prop.attack = self.baseProp.attack + self.extendProp.attack
	self.prop.defense = self.baseProp.defense + self.extendProp.defense
	self.prop.critAttack = self.baseProp.critAttack + self.extendProp.critAttack
	self.prop.critDefense = self.baseProp.critDefense + self.extendProp.critDefense
	self.prop.critDamageAttack = self.baseProp.critDamageAttack + self.extendProp.critDamageAttack
	self.prop.critDamageDefense = self.baseProp.critDamageDefense + self.extendProp.critDamageDefense
end
--- 判断是否是玩家
---@return boolean
function M:IsPlayer()
	return self.entityType == CombatState.EntityType.Player
end

--- 判断是否是敌人
---@return boolean
function M:IsEnemy()
	return self.entityType == CombatState.EntityType.Enemy
end

--- 添加Buff
---@param buffId number BuffID
---@param duration number 持续回合数
function M:AddBuff(buffId, duration)
	--这里需要处理叠、覆盖规则
	self.buffs[buffId] = {
		id = buffId,
		duration = duration,
		stackCount = 1
	}

end

--- 移除Buff
---@param buffId number BuffID
function M:RemoveBuff(buffId)
	self.buffs[buffId] = nil
end

--- 减少Buff持续时间
function M:DecrementBuffDuration()
	for buffId, buff in pairs(self.buffs) do
		buff.duration = buff.duration - 1
		if buff.duration <= 0 then
			self.buffs[buffId] = nil
		end
	end
end

--- 添加技能
---@param skillId number 技能ID
---@param skillData table 技能数据
function M:AddSkill(skillId, skillData)
	self.skills[skillId] = skillData
end

--- 获取技能
---@param skillId number 技能ID
---@return table|nil
function M:GetSkill(skillId)
	return self.skills[skillId]
end

--- 获取所有技能
---@return table
function M:GetAllSkills()
	return self.skills
end

--- 自动选择一个技能
function M:GetAutoSkill()
	for _, skill in pairs(self.skills) do
		--临时放第一个
		return skill
	end
end

--- 计算行动值增长
---@param speed fixed 速度值
---@return fixed
function M:CalcActionValueGrowth(speed)
	-- 类似崩铁的行动值计算：速度越快，行动值减少越快
	return speed * Fix.new(100)
end

--- 获取当前HP百分比
---@return fixed
function M:GetHpPercent()
	if self.prop.maxHp <= CombatConst.zero then
		return Fix.new(0)
	end
	return self.prop.hp / self.prop.maxHp
end

--- 受到伤害
---@param damage fixed 伤害值
function M:TakeDamage(damage)
	self.prop.hp = self.prop.hp - damage
	if self.prop.hp <= Fix.new(0) then
		self.prop.hp = Fix.new(0)
		self.prop.isDead = true
	end
end

--- 恢复生命
---@param heal fixed 治疗值
function M:Heal(heal)
	self.prop.hp = self.prop.hp + heal
	if self.prop.hp > self.prop.maxHp then
		self.prop.hp = self.prop.maxHp
	end
	if self.prop.isDead and self.prop.hp > Fix.new(0) then
		self.prop.isDead = false
	end
end

--- 重置行动值
function M:ResetActionValue()
	self.prop.actionValue = self.prop.baseActionValue
end

--- 消耗行动值
---@param amount fixed
function M:ConsumeActionValue(amount)
	self.prop.actionValue = self.prop.actionValue - amount
end

return M