---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---


local LuaHelper = require("Utility.LuaHelper")
local Fix = require("lfixed")

---@class CombatProp
local M = LuaHelper.LuaClass()

function M:__OnNew(prop)
	self.hp = Fix.new(prop.hp or 0)
	self.maxHp = Fix.new(prop.maxHp or prop.hp or 0)
	self.attack = Fix.new(prop.attack or 0)
	self.defense = Fix.new(prop.defense or 0)
	self.actionValue = Fix.new(prop.actionValue or 0)
	self.critAttack = Fix.new(prop.critAttack)
	self.critDefense = Fix.new(prop.critDefense)
	self.critDamageAttack = Fix.new(prop.critDamageAttack)
	self.critDamageDefense = Fix.new(prop.critDamageDefense)
end

return M