---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---


local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")
local CombatProp = require("GamePlay.Combat.GameLogic.CombatProp")
local CombatConst = require("GamePlay.Combat.GameLogic.CombatConst")
local Buff = require("GamePlay.Combat.GameLogic.Buff")
local CombatEvent = require("GamePlay.Combat.GameLogic.CombatEvent")

---@class CombatEntity
local M = LuaHelper.LuaClass()

function M:__OnNew(manager, id, position, entityType, prop)
	self.id = id
	self.combatManager = manager
	self.entityType = entityType or CombatState.EntityType.Player
	self.baseProp = CombatProp:New(prop or {})
	self.extendProp = CombatProp:New({})
	self.prop = CombatProp:New({})
	self.position = position or 0
	self.buffs = {}
	self.skills = {}
	self.buffEventHandlers = {} -- 存储触发Buff的事件处理器
	self.position = prop.position or 0
	self.name = prop.name or ("Entity_" .. id)

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.CombatEntityCreate)
	eventData.source = self
	CombatEvent.Publish(CombatEvent.EventType.AfterDamage, eventData)
	
end

--- 判断是否存活
---@return boolean
function M:IsAlive()
	return not self.prop.isDead
end
--- 获取战斗管理器
---@return CombatManager
function M:BattleManager()
	return self.combatManager
end

function M:CalcProp()
	self.prop = CombatProp:New({})

	self.prop.maxHp = self.baseProp.maxHp + self.petProp.maxHp + self.extendProp.maxHp
	self.prop.attack = self.baseProp.attack + self.extendProp.attack
	self.prop.defense = self.baseProp.defense + self.extendProp.defense
	self.prop.critAttack = self.baseProp.critAttack + self.extendProp.critAttack
	self.prop.critDefense = self.baseProp.critDefense + self.extendProp.critDefense
	self.prop.critDamageAttack = self.baseProp.critDamageAttack + self.extendProp.critDamageAttack
	self.prop.critDamageDefense = self.baseProp.critDamageDefense + self.extendProp.critDamageDefense
end

-- 刷新Buff后需要重新计算属性
--- 注意：此方法只处理属性Buff，不会调用触发Buff的ApplyEffect
function M:RefreshBuff()
	self.extendProp = CombatProp:New({})
	
	-- 累加所有属性Buff的修正值
	for _, buff in pairs(self.buffs) do
		if buff.category == Buff.BuffCategory.Stat then
			local modifier = buff:GetStatModifier()
			
			-- 累加所有属性（无需 if 判断，nil 或 0 相加结果正确）
			self.extendProp.hp = self.extendProp.hp + modifier.hp
			self.extendProp.maxHp = self.extendProp.maxHp + modifier.maxHp
			self.extendProp.attack = self.extendProp.attack + modifier.attack
			self.extendProp.defense = self.extendProp.defense + modifier.defense
			self.extendProp.speed = self.extendProp.speed + modifier.speed
			self.extendProp.critAttack = self.extendProp.critAttack + modifier.critAttack
			self.extendProp.critDefense = self.extendProp.critDefense + modifier.critDefense
			self.extendProp.critDamageAttack = self.extendProp.critDamageAttack + modifier.critDamageAttack
			self.extendProp.critDamageDefense = self.extendProp.critDamageDefense + modifier.critDamageDefense
		end
    end
	
	self:CalcProp()
end
--- 判断是否是玩家
---@return boolean
function M:IsPlayer()
	return self.entityType == CombatState.EntityType.Player
end

--- 判断是否是敌人
---@return boolean
function M:IsEnemy()
	return self.entityType == CombatState.EntityType.Enemy
end

--- 添加Buff
---@param source CombatEntity 攻击者
---@param buff  
function M:AddBuff(source, buff)
	--这里需要处理叠、覆盖规则
	buff:SetTarget(source, self)
	
	-- 即时Buff：立即执行效果，不保存到buffs列表
	if buff.category == Buff.BuffCategory.Instant then
		buff:ApplyEffect()
		print("[CombatEntity] Instant buff applied:", buff.name)
		return
	end
	
	-- 属性Buff和触发Buff：保存到buffs列表
	self.buffs[buff.id] = buff
	
	-- 属性Buff：刷新属性
	if buff.category == Buff.BuffCategory.Stat then
		self:RefreshBuff()
	end
	
	-- 触发Buff：订阅相应事件
	if buff.category == Buff.BuffCategory.Trigger and buff.triggerEvent then
		local handler = function(eventData)
			buff:ApplyEffect(eventData)
		end
		CombatEvent.Subscribe(buff.triggerEvent, handler, self)
		
		-- 保存事件处理器引用，以便后续取消订阅
		self.buffEventHandlers[buff.id] = {
			eventType = buff.triggerEvent,
			handler = handler
		}
		
		print("[CombatEntity] Trigger buff added:", buff.name, "event:", buff.triggerEvent)
	end
end

--- 移除Buff
---@param buffId number BuffID
function M:RemoveBuff(buffId)
	local buff = self.buffs[buffId]
	if not buff then
		return
	end
	
	-- 如果是触发Buff，取消事件订阅
	if buff.category == Buff.BuffCategory.Trigger then
		local eventHandler = self.buffEventHandlers[buffId]
		if eventHandler then
			CombatEvent.Unsubscribe(eventHandler.eventType, eventHandler.handler)
			self.buffEventHandlers[buffId] = nil
			print("[CombatEntity] Trigger buff removed:", buff.name, "unsubscribed event:", eventHandler.eventType)
		end
	end
	
	-- 移除Buff
	self.buffs[buffId] = nil
	
	-- 如果是属性Buff，刷新属性
	if buff.category == Buff.BuffCategory.Stat then
		self:RefreshBuff()
	end
end

--- 减少Buff持续时间
function M:DecrementBuffDuration()
	for buffId, buff in pairs(self.buffs) do
		buff.duration = buff.duration - 1
		if buff.duration <= 0 then
			self:RemoveBuff(buffId)
		end
	end
end

--- 添加技能
---@param skillId number 技能ID
---@param skillData table 技能数据
function M:AddSkill(skillId, skillData)
	self.skills[skillId] = skillData
end

--- 获取技能
---@param skillId number 技能ID
---@return table|nil
function M:GetSkill(skillId)
	return self.skills[skillId]
end

--- 获取所有技能
---@return table
function M:GetAllSkills()
	return self.skills
end

--- 自动选择一个技能
function M:GetAutoSkill()
	for _, skill in pairs(self.skills) do
		--临时放第一个
		return skill
	end
end

--- 计算行动值增长
---@param speed fixed 速度值
---@return fixed
function M:CalcActionValueGrowth(speed)
	-- 类似崩铁的行动值计算：速度越快，行动值减少越快
	return speed * Fix.new(100)
end

--- 获取当前HP百分比
---@return fixed
function M:GetHpPercent()
	if self.prop.maxHp <= CombatConst.zero then
		return CombatConst.zero
	end
	return self.prop.hp / self.prop.maxHp
end

--- 受到伤害
---@param damage fixed 伤害值
function M:TakeDamage(damage)
	self.prop.hp = self.prop.hp - damage
	if self.prop.hp <= CombatConst.zero then
		self.prop.hp = CombatConst.zero
		self.prop.isDead = true
	end
end

--- 恢复生命
---@param heal fixed 治疗值
function M:Heal(heal)
	self.prop.hp = self.prop.hp + heal
	if self.prop.hp > self.prop.maxHp then
		self.prop.hp = self.prop.maxHp
	end
	if self.prop.isDead and self.prop.hp > CombatConst.zero then
		self.prop.isDead = false
	end
end

--- 重置行动值
function M:ResetActionValue()
	self.prop.actionValue = self.prop.baseActionValue
end

--- 消耗行动值
---@param amount fixed
function M:ConsumeActionValue(amount)
	self.prop.actionValue = self.prop.actionValue - amount
end

--- 清理所有Buff事件订阅
function M:ClearBuffEventHandlers()
	for buffId, eventHandler in pairs(self.buffEventHandlers) do
		CombatEvent.Unsubscribe(eventHandler.eventType, eventHandler.handler)
	end
	self.buffEventHandlers = {}
end

return M