---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---

local CombatState = require("GamePlay.Combat.GameLogic.CombatState")

---@class CombatEvent
local M = {}

--- 事件类型定义
M.EventType = {
	-- 战斗生命周期事件
	BattleInitialize = 1, -- 战斗数据初始化
	BattleStart = 2, -- 战斗开始
	BattleEnd = 3, -- 战斗结束

	-- 回合事件
	RoundStart = 10, -- 回合开始
	TurnStart = 11, -- 角色回合开始
	TurnEnd = 12, -- 角色回合结束

	-- 行动事件
	ActionStart = 20, -- 角色行动开始
	ActionEnd = 21, -- 角色行动结束

	-- 攻击事件
	AttackStart = 30, -- 角色开始攻击流程
	AttackEffect = 31, -- 角色攻击生效
	AttackEnd = 32, -- 角色攻击完成

	-- 伤害事件
	BeforeDamage = 40, -- 伤害生效前
	DealDamage = 41, -- 造成伤害
	AfterDamage = 42, -- 伤害生效后

	-- 技能事件
	SkillCast = 50, -- 技能释放
	SkillEffect = 51, -- 技能生效

	-- 状态事件
	BuffAdd = 60, -- 添加Buff
	BuffRemove = 61, -- 移除Buff
	BuffTrigger = 62, -- Buff触发

	-- 其他事件
	OpenSkillCheck = 70, -- 开场技能检测
	ActionValueCalc = 71, -- 行动值计算
	BattleEndCheck = 72, -- 战斗是否结束判断

	ManualSkillInput = 80, -- 手动技能输入
}

--- 事件处理器表
local eventHandlers = {}

--- 订阅事件
---@param eventType number 事件类型
---@param handler function 事件处理函数
---@param context any 上下文对象
function M.Subscribe(eventType, handler, context)
	if not eventHandlers[eventType] then
		eventHandlers[eventType] = {}
	end
	table.insert(eventHandlers[eventType], {
		handler = handler,
		context = context
	})
end

--- 取消订阅事件
---@param eventType number 事件类型
---@param handler function 事件处理函数
---@param context any 上下文对象
function M.Unsubscribe(eventType, handler, context)
	if not eventHandlers[eventType] then
		return
	end

	for i = #eventHandlers[eventType], 1, -1 do
		local h = eventHandlers[eventType][i]
		if h.handler == handler and h.context == context then
			table.remove(eventHandlers[eventType], i)
			break
		end
	end
end

--- 发布事件
---@param eventType number 事件类型
---@param eventData table 事件数据
function M.Publish(eventType, eventData)
	if not eventHandlers[eventType] then
		return
	end

	for _, h in ipairs(eventHandlers[eventType]) do
		local success, err = pcall(h.handler, eventData, h.context)
		if not success then
			print("[CombatEvent] Error in event handler:", err)
		end
	end
end

--- 清除所有事件处理器
function M.ClearAll()
	eventHandlers = {}
end

--- 创建事件数据
---@param eventType number 事件类型
---@return table eventData
function M.CreateEventData(eventType)
	return {
		eventType = eventType,
		timestamp = os.time(),
		-- 通用字段
		source = nil, -- 事件源实体
		target = nil, -- 目标实体
		value = nil, -- 数值
		-- 战斗相关字段
		battleState = nil, -- 战斗状态
		currentTurn = nil, -- 当前回合数
		currentActor = nil, -- 当前行动实体
		-- 攻击相关字段
		attacker = nil, -- 攻击者
		defender = nil, -- 防御者
		damage = nil, -- 伤害值
		damageType = nil, -- 伤害类型
		isCritical = false, -- 是否暴击
		-- 技能相关字段
		skillId = nil, -- 技能ID
		skillLevel = nil, -- 技能等级
		-- Buff相关字段
		buffId = nil, -- BuffID
		buffDuration = nil, -- Buff持续时间
		-- 回合相关字段
		round = nil, -- 回合数
		actionValue = nil, -- 行动值
	}
end

return M
