---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created liujinchun.ljc
--- DateTime: 2026/03/02 14:03
---

local Fix = require("lfixed")

--- 创建不可修改的常量表
local function createReadonlyTable(t)
    local metatable = {
        __index = t,
        __newindex = function(_, key, value)
            error("[CombatConst] Attempt to modify constant '" .. tostring(key) .. "' with value " .. tostring(value), 2)
        end,
        __metatable = false -- 防止获取或修改元表
    }
    return setmetatable({}, metatable)
end

--- 原表：定义所有常量
local M = {
    zero = Fix.new(0),
    minCritDamage = Fix.new(1.5)
}

--- 属性类型枚举（用于 Buff 配置中的属性 ID）
M.PropType = {
    Hp = 1,
    MaxHp = 2,
    Attack = 3,
    Defense = 4,
    Speed = 5,
    CritAttack = 6,
    CritDefense = 7,
    CritDamageAttack = 8,
    CritDamageDefense = 9
}

--- 属性类型到属性名的映射表
M.PropTypeToName = {
    [M.PropType.Hp] = "hp",
    [M.PropType.MaxHp] = "maxHp",
    [M.PropType.Attack] = "attack",
    [M.PropType.Defense] = "defense",
    [M.PropType.Speed] = "speed",
    [M.PropType.CritAttack] = "critAttack",
    [M.PropType.CritDefense] = "critDefense",
    [M.PropType.CritDamageAttack] = "critDamageAttack",
    [M.PropType.CritDamageDefense] = "critDamageDefense"
}

--- 返回只读的常量表
return createReadonlyTable(M)