
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---

---@class CombatState
local M = {}

--- 战斗状态枚举
M.BattleState = {
    Idle = 0,           -- 空闲状态
    Initializing = 1,   -- 初始化中
    InBattle = 2,       -- 战斗中
    RoundStart = 3,     -- 回合开始
    TurnStart = 4,      -- 角色回合开始
    ActionStart = 5,    -- 行动开始
    Attacking = 6,      -- 攻击中
    DamageCalc = 7,     -- 伤害计算中
    ActionEnd = 8,      -- 行动结束
    TurnEnd = 9,        -- 角色回合结束
    BattleEnd = 10,     -- 战斗结束
}
--- 目标类型
M.TargetType = {
	Self = 0,
	SelfTeam = 1,
	Target = 2,
	TargetTeam = 3,
}


--- 战斗结果枚举
M.BattleResult = {
    None = 0,           -- 未结束
    Victory = 1,        -- 胜利
    Defeat = 2,         -- 失败
    Draw = 3,           -- 平局
}

--- 实体类型枚举
M.EntityType = {
    Player = 1,         -- 玩家
    Enemy = 2,          -- 敌人
}

--- 行动阶段枚举
M.ActionPhase = {
    None = 0,           -- 无
    RoundStart = 1,     -- 回合开始阶段
    TurnStart = 2,      -- 角色回合开始阶段
    ActionStart = 3,    -- 角色行动开始阶段
    AttackStart = 4,    -- 角色开始攻击阶段
    AttackEffect = 5,   -- 角色攻击生效阶段
    BeforeDamage = 6,   -- 伤害生效前阶段
    DealDamage = 7,     -- 造成伤害阶段
    AfterDamage = 8,    -- 伤害生效后阶段
    AttackEnd = 9,      -- 角色攻击完成阶段
    ActionEnd = 10,     -- 角色行动结束阶段
    TurnEnd = 11,       -- 角色回合结束阶段
}

--- 行为类型枚举
M.ActionType = {
    Skill = 1,          -- 技能行为
    Buff = 2,           -- Buff行为
}

return M