---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---

local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")
local CombatEvent = require("GamePlay.Combat.GameLogic.CombatEvent")
local CombatRound = require("GamePlay.Combat.GameLogic.CombatRound")
local CombatConst = require("GamePlay.Combat.GameLogic.CombatConst")
local BattleLog = require("GamePlay.Combat.GameLogic.BattleLog")
local Formula = require("GamePlay.Combat.GameLogic.Formula")
local CombatInput = require("GamePlay.Combat.GameLogic.CombatInput")
local CombatEntity = require("GamePlay.Combat.GameLogic.CombatEntity")

local BATTLE_VERSION = "2026.02.27"
---@class CombatManager
local M = LuaHelper.LuaClass()

function M:__OnNew(operate)
	--- 创建并管理 roundManager
	self.roundManager = CombatRound:New()
	self.roundManager:SetCombatManager(self)
	self.randomGenerator = nil
	self.battleLog = BattleLog:New()
	self.battleState = CombatState.BattleState.Idle
	self.battleResult = CombatState.BattleResult.None
	self.config = {}
	self.inputManager = CombatInput:New(CombatInput.InputMode.Auto, operate)
	self.isPaused = false
	self.currentEntity = nil

	Formula.CombatManager = self;
	print("[CombatSystem] Initialized, version:", BATTLE_VERSION)

	self:CreateTestPlayers()
	CombatEvent.Subscribe(CombatEvent.EventType.BattleInitialize, self.InitPlayers, self)
end

--- 反初始化战斗管理器
function M:Deinitialize()
	CombatEvent.Unsubscribe(CombatEvent.EventType.BattleInitialize, self.InitPlayers)

	if self.roundManager then
		self.roundManager:Reset()
		self.roundManager = nil
	end
	if self.battleLog then
		self.battleLog:Clear()
		self.battleLog = nil
	end
	self.randomGenerator = nil
	self.battleState = CombatState.BattleState.Idle
	self.battleResult = CombatState.BattleResult.None
	self.config = {}
	Formula.CombatManager = nil
end

function M:InitPlayers(eventData)
	local players = eventData.customization
	if players == nil then
		return
	end
	for i, player in ipairs(players.player) do
		local entity = CombatEntity:New(self, player.id, player.position, CombatState.EntityType.Player, player.propData)
		self.roundManager:RegisterEntity(entity)
	end

	for i, enemy in ipairs(players.enemy) do
		local entity = CombatEntity:New(self, enemy.id, enemy.position, CombatState.EntityType.Enemy, enemy.propData)
		self.roundManager:RegisterEntity(entity)
	end
end

--- 开始战斗流程
function M:StartBattle(endPlayCallback)
	print("[CombatManager] Start Battle ====================================")

	--- 步骤1: 战斗数据初始化
	self:SetBattleState(CombatState.BattleState.Initializing)
	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.BattleInitialize)
	eventData.battleState = self:GetBattleState()
	eventData.customization = self.testPlayers
	CombatEvent.Publish(CombatEvent.EventType.BattleInitialize, eventData)

	--- 步骤2: 战斗开始
	self:SetBattleState(CombatState.BattleState.InBattle)
	eventData = CombatEvent.CreateEventData(CombatEvent.EventType.BattleStart)
	eventData.battleState = self:GetBattleState()
	CombatEvent.Publish(CombatEvent.EventType.BattleStart, eventData)

	--- 步骤3: 开场技能检测
	self:CheckOpenSkill()

	--- 根据输入模式选择战斗循环
	if self.inputManager:GetMode() == CombatInput.InputMode.Verify then
		--- Verify 模式：使用自动循环
		self:RunBattleLoopAuto(endPlayCallback)
	else
		--- Manual 和 Auto 模式：使用手动循环（逐个回合生成）
		self:RunBattleLoopManual(endPlayCallback)
	end
end

--- 主战斗循环（自动循环，用于 Verify 模式）
function M:RunBattleLoopAuto(endPlayCallback)
	local test = 0
	while test < 10 do
		test = test + 1
		--- 步骤21: 战斗是否结束判断
		self.battleResult = self.roundManager:CheckBattleEnd()
		if self.battleResult ~= CombatState.BattleResult.None then
			if endPlayCallback then
				endPlayCallback(self.battleResult)
			end
			break
		end
		
		--- 步骤4: 行动值计算
 		self:CalculateActionValues()
		
		--- 步骤5: 进入角色回合
		local curEntity = self.roundManager:GetNextEntity()
		if not curEntity then
			break
		end

		self.roundManager:SetCurrentEntity(curEntity)

		--- 执行单个回合
		if not self.roundManager:ExecuteRound(curEntity, self.inputManager) then
			break
		end
	end
end

--- 手动战斗循环（逐个回合生成，支持暂停等待）
function M:RunBattleLoopManual(endPlayCallback)
	--- 如果暂停，直接返回等待外部输入
	if self.isPaused then
		if self.inputManager:IsInputCompleted() then
			self.isPaused = false
			self.currentEntity = nil
		end
		return
	end

	--- 步骤21: 战斗是否结束判断
	self.battleResult = self.roundManager:CheckBattleEnd()
	if self.battleResult ~= CombatState.BattleResult.None then
		if endPlayCallback then
			endPlayCallback(self.battleResult)
		end
		return
	end

	--- 步骤4: 行动值计算
	self:CalculateActionValues()

	--- 步骤5: 进入角色回合
	local currentEntity = self.roundManager:GetNextEntity()
	if not currentEntity then
		return
	end

	self.roundManager:SetCurrentEntity(currentEntity)

	--- 执行单个回合
	self.roundManager:ExecuteRound(currentEntity, self.inputManager)
end

--- 检测开场技能
function M:CheckOpenSkill()
	print("[CombatManager] Step 3: Check Open Skill")

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.OpenSkillCheck)
	eventData.round = self.roundManager:GetCurrentRound()
	CombatEvent.Publish(CombatEvent.EventType.OpenSkillCheck, eventData)
end

--- 计算行动值
function M:CalculateActionValues()
	print("[CombatManager] Calculate Action Values")

	--- 计算所有实体的行动值增长
	local allEntities = self.roundManager:GetAllEntities()
	
	--- 为每个实体添加原始索引，用于稳定排序
	for i, entity in ipairs(allEntities) do
		entity._sortIndex = i
	end
	
	--- 稳定排序：actionValue 相等时保持原始顺序
	table.sort(allEntities, function(a, b)
		if a.prop.actionValue ~= b.prop.actionValue then
			return a.prop.actionValue < b.prop.actionValue
		else
			return a._sortIndex < b._sortIndex
		end
	end)
	
	self.roundManager.entities = allEntities
	local firstEntity = allEntities[1]
	local cost = firstEntity.prop.actionValue
	if cost == CombatConst.zero then
		firstEntity.prop.actionValue = CombatConst.actionBase / firstEntity.prop.spd
		for i, entity in ipairs(allEntities) do
			entity.index = i
		end
		
		table.sort(allEntities, function(a, b)
			if a.prop.actionValue ~= b.prop.actionValue then
				return a.prop.actionValue < b.prop.actionValue
			else
				return a.index < b.index
			end
		end)
	end

	for _, entity in ipairs(allEntities) do
		if entity:IsAlive() then
			entity:ConsumeActionValue(cost)
		end
		
		print("sssssssssssssssss  ", entity.name, ": ", entity.prop.actionValue)
	end

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.ActionValueCalc)
	eventData.round = self.roundManager:GetCurrentRound()
	CombatEvent.Publish(CombatEvent.EventType.ActionValueCalc, eventData)
end

--- 角色回合开始（事件发布）
---@param entity CombatEntity
function M:OnTurnStart(entity)
	print("[CombatManager] Turn Start:", entity.name)

	self.battleState = CombatState.BattleState.TurnStart

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.TurnStart)
	eventData.currentEntity = entity
	eventData.round = self.roundManager:GetCurrentRound()
	eventData.actionValue = entity.prop.actionValue:ToNumber()
	CombatEvent.Publish(CombatEvent.EventType.TurnStart, eventData)
end

--- 随机数接口
function M:Random()
	return self.randomGenerator:Next()
end

function M:RandomFloat()
	return self.randomGenerator:NextFloat()
end

function M:RandomFixed()
	return self.randomGenerator:NextFixed()
end

function M:RandomRange(min, max)
	return self.randomGenerator:NextRange(min, max)
end

function M:RandomRangeFixed(min, max)
	return self.randomGenerator:NextRangeFixed(min, max)
end

function M:RandomRangeFloat(min, max)
	return self.randomGenerator:NextRangeFloat(min, max)
end

function M:Choice(array)
	return self.randomGenerator:Choice(array)
end

--- 获取当前战斗状态
---@return number
function M:GetBattleState()
	return self.battleState
end

--- 设置战斗状态
---@param state number
function M:SetBattleState(state)
	self.battleState = state
end

--- 获取回合管理器
---@return CombatRound
function M:GetRoundManager()
	return self.roundManager
end

--- 获取战斗结果
---@return number
function M:GetBattleResult()
	return self.battleResult
end

--- 添加技能到实体
---@param entityId number 实体ID
---@param skillData table 技能数据
function M:AddSkillToEntity(entityId, skillData)
	local entity = self:GetEntityById(entityId)
	if entity then
		local skill = Skill:New(skillData)
		entity:AddSkill(skillData.id, skill)
		print("[CombatManager] Added skill", skillData.id, "to entity", entityId)
	else
		print("[CombatManager] Failed to add skill - entity not found:", entityId)
	end
end

--- 添加Buff到实体
---@param entityId number 实体ID
---@param buffData table Buff数据
function M:AddBuffToEntity(entityId, buffData)
	local entity = self:GetEntityById(entityId)
	if entity then
		local buff = Buff:New(buffData)
		entity:AddBuff(entity, buff)

		--- 记录Buff行动到战斗日志
		self.battleLog:LogBuffAction(entityId, buffData.id, buffData.effectType or "none", buffData.effectValue or 0)

		print("[CombatManager] Added buff", buffData.id, "to entity", entityId)
	else
		print("[CombatManager] Failed to add buff - entity not found:", entityId)
	end
end

--- 根据ID获取实体（委托给 CombatRound）
---@param entityId number 实体ID
---@return CombatEntity|nil
function M:GetEntityById(entityId)
	return self.roundManager:GetEntityById(entityId)
end

--- 获取实体的技能
---@param entityId number 实体ID
---@param skillId number 技能ID
---@return Skill|nil
function M:GetEntitySkill(entityId, skillId)
	local entity = self:GetEntityById(entityId)
	if entity then
		return entity:GetSkill(skillId)
	end
	return nil
end

--- 获取实体的所有技能
---@param entityId number 实体ID
---@return table
function M:GetEntityAllSkills(entityId)
	local entity = self:GetEntityById(entityId)
	if entity then
		return entity:GetAllSkills()
	end
	return {}
end

--- 获取实体的Buff
---@param entityId number 实体ID
---@param buffId number BuffID
---@return Buff|nil
function M:GetEntityBuff(entityId, buffId)
	local entity = self:GetEntityById(entityId)
	if entity and entity.buffs then
		return entity.buffs[buffId]
	end
	return nil
end

--- 移除实体的Buff
---@param entityId number 实体ID
---@param buffId number BuffID
function M:RemoveEntityBuff(entityId, buffId)
	local entity = self:GetEntityById(entityId)
	if entity then
		entity:RemoveBuff(buffId)
		print("[CombatManager] Removed buff", buffId, "from entity", entityId)
	end
end

--- 战斗记录相关方法

--- 开始新回合记录
---@param roundIndex number 回合索引
function M:StartRoundLog(roundIndex)
	self.battleLog:StartRound(roundIndex)
end

--- 结束当前回合记录
function M:EndRoundLog()
	self.battleLog:EndRound()
end

--- 记录技能行动
---@param attackerId number 攻击者ID
---@param skillId number 技能ID
---@param targetIds table 目标ID列表
---@param damages table 伤害列表
---@param weakness table 弱点列表
function M:LogSkillAction(attackerId, skillId, targetIds, damages, weakness)
	self.battleLog:LogSkillAction(attackerId, skillId, targetIds, damages, weakness)
end

--- 记录Buff行动
---@param targetId number 目标ID
---@param buffId number BuffID
---@param effectType string 效果类型
---@param effectValue number 效果值
function M:LogBuffAction(targetId, buffId, effectType, effectValue)
	self.battleLog:LogBuffAction(targetId, buffId, effectType, effectValue)
end

--- 输出当前回合战斗记录
function M:PrintCurrentRoundLog()
	self.battleLog:PrintCurrentRoundLog()
end

--- 输出所有回合战斗记录
function M:PrintAllRoundLogs()
	self.battleLog:PrintAllRoundLogs()
end

--- 获取当前回合日志
---@return table
function M:GetCurrentRoundLog()
	return self.battleLog:GetCurrentRoundLog()
end

--- 获取所有回合日志
---@return table
function M:GetAllRoundLogs()
	return self.battleLog:GetAllRoundLogs()
end

--- 获取指定回合日志
---@param roundIndex number 回合索引
---@return table|nil
function M:GetRoundLog(roundIndex)
	return self.battleLog:GetRoundLog(roundIndex)
end

--- 获取战斗日志对象
---@return BattleLog
function M:GetBattleLog()
	return self.battleLog
end

--- 模拟战斗玩家
function M:CreateTestPlayers()
	local player1 = {
		id = 1,
		position = 1,
		type = CombatState.EntityType.Player,
		propData = {
			propId = 10001,
			level = 1
		}
	}

	local player2 = {
		id = 2,
		position = 2,
		type = CombatState.EntityType.Player,
		propData = {
			propId = 10001,
			level = 10
		}
	}

	local enemy1 = {
		id = 10001,
		position = 3,
		type = CombatState.EntityType.Enemy,
		propData = {
			propId = 10002,
			level = 1
		}
	}

	local enemy2 = {
		id = 10002,
		position = 4,
		type = CombatState.EntityType.Enemy,
		propData = {
			propId = 10002,
			level = 10
		}
	}

	self.testPlayers = {
		player = { player1, player2 },
		enemy = { enemy1, enemy2 }
	}
end

return M