---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---
---@class CombatState
local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")

---@class CombatRound
local M = LuaHelper.LuaClass()

function M:__OnNew()
	self.entities = {}
	self.currentRound = 0
	self.currentActor = nil
	self.actionQueue = {}
end

--- 注册战斗实体
---@param entity CombatEntity
function M:RegisterEntity(entity)
	table.insert(self.entities, entity)
	-- 初始化行动值
	entity:ResetActionValue()
end

--- 获取所有实体
---@return table
function M:GetAllEntities()
	return self.entities
end

--- 获取存活的实体
---@return table
function M:GetAliveEntities()
	local aliveEntities = {}
	for _, entity in ipairs(self.entities) do
		if entity:IsAlive() then
			table.insert(aliveEntities, entity)
		end
	end
	return aliveEntities
end

--- 获取存活的玩家实体
---@return table
function M:GetAlivePlayers()
	local players = {}
	for _, entity in ipairs(self.entities) do
		if entity:IsAlive() and entity:IsPlayer() then
			table.insert(players, entity)
		end
	end
	return players
end

--- 获取存活的敌人实体
---@return table
function M:GetAliveEnemies()
	local enemies = {}
	for _, entity in ipairs(self.entities) do
		if entity:IsAlive() and entity:IsEnemy() then
			table.insert(enemies, entity)
		end
	end
	return enemies
end

--- 计算所有实体的行动值增长
function M:CalculateActionValues()
	for _, entity in ipairs(self.entities) do
		if entity:IsAlive() then
			local growth = entity:CalcActionValueGrowth(entity.prop.speed)
			entity:ConsumeActionValue(growth)
		end
	end
end

--- 获取下一个行动的实体
---@return CombatEntity|nil
function M:GetNextActor()
	local aliveEntities = self:GetAliveEntities()
	if #aliveEntities == 0 then
		return nil
	end

	-- 找到行动值最小的实体
	local nextActor = nil
	local minActionValue = nil

	for _, entity in ipairs(aliveEntities) do
		if minActionValue == nil or entity.prop.actionValue < minActionValue then
			minActionValue = entity.prop.actionValue
			nextActor = entity
		end
	end

	return nextActor
end

--- 开始新的回合
function M:StartNewRound()
	self.currentRound = self.currentRound + 1
end

--- 设置当前行动实体
---@param entity CombatEntity
function M:SetCurrentActor(entity)
	self.currentActor = entity
end

--- 获取当前行动实体
---@return CombatEntity|nil
function M:GetCurrentActor()
	return self.currentActor
end

--- 获取当前回合数
---@return number
function M:GetCurrentRound()
	return self.currentRound
end

--- 检查战斗是否结束
---@return number 战斗结果
function M:CheckBattleEnd()
	local alivePlayers = self:GetAlivePlayers()
	local aliveEnemies = self:GetAliveEnemies()

	if #alivePlayers == 0 and #aliveEnemies == 0 then
		return CombatState.BattleResult.Draw
	elseif #alivePlayers == 0 then
		return CombatState.BattleResult.Defeat
	elseif #aliveEnemies == 0 then
		return CombatState.BattleResult.Victory
	else
		return CombatState.BattleResult.None
	end
end

--- 重置回合管理器
function M:Reset()
	self.entities = {}
	self.currentRound = 0
	self.currentActor = nil
	self.actionQueue = {}
end

return M