---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created liujinchun.ljc
--- DateTime: 2026/03/02 14:03
---

local Fix = require("lfixed")

--- 创建不可修改的常量表
local function createReadonlyTable(t)
    local metatable = {
        __index = t,
        __newindex = function(_, key, value)
            error("[CombatConst] Attempt to modify constant '" .. tostring(key) .. "' with value " .. tostring(value), 2)
        end,
        __metatable = false -- 防止获取或修改元表
    }
    return setmetatable({}, metatable)
end

--- 原表：定义所有常量
local M = {
    zero = Fix.new(0),
    minCritDamage = Fix.new(1.5),
	actionBase = Fix.new(10000)
}

--- 属性类型枚举（用于 Buff 配置中的属性 ID）
M.PropType = {
	Hp = 1,
	MaxHp = 2,
	Atk = 3,
	Def = 4,
	Crit = 5,
	CritDef = 6,
	CritDamage = 7,
	CritDamageDef = 8,
	Miss = 9,
	HitOdds = 10,
	Spd = 11,
	DamageAmp = 12,
	DamageRd = 13,
	HpPercent = 14,
	AtkPercent = 15,
	DefPercent = 16,
	SkillInc = 17,
	SkillRd = 18,
	BreakInc = 19
}

--- 属性类型到属性名的映射表
M.PropTypeToName = {
    [M.PropType.Hp] = "hp",
    [M.PropType.MaxHp] = "maxHp",
    [M.PropType.Atk] = "atk",
    [M.PropType.Def] = "def",
    [M.PropType.Crit] = "crit",
    [M.PropType.CritDef] = "critDef",
    [M.PropType.CritDamage] = "critDamage",
    [M.PropType.CritDamageDef] = "critDamageDef",
    [M.PropType.Miss] = "miss",
    [M.PropType.HitOdds] = "hitOdds",
    [M.PropType.Spd] = "spd",
    [M.PropType.DamageAmp] = "damageAmp",
    [M.PropType.DamageRd] = "damageRd",
    [M.PropType.HpPercent] = "hpPercent",
    [M.PropType.AtkPercent] = "atkPercent",
    [M.PropType.DefPercent] = "defPercent",
    [M.PropType.SkillInc] = "skillInc",
    [M.PropType.SkillRd] = "skillRd",
    [M.PropType.BreakInc] = "breakInc"
}

--- 返回只读的常量表
return createReadonlyTable(M)