---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---

local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")
local CombatEvent = require("GamePlay.Combat.GameLogic.CombatEvent")
local CombatRound = require("GamePlay.Combat.GameLogic.CombatRound")
local Skill = require("GamePlay.Combat.GameLogic.Skill")
local Buff = require("GamePlay.Combat.GameLogic.Buff")
local BattleLog = require("GamePlay.Combat.GameLogic.BattleLog")
local Formula = require("GamePlay.Combat.GameLogic.Formula")
local CombatInput = require("GamePlay.Combat.GameLogic.CombatInput")
local Fix = require("lfixed")

local BATTLE_VERSION = "2026.02.27"
---@class CombatManager
local M = LuaHelper.LuaClass()

function M:__OnNew(players, operate)
	--- 创建并管理 roundManager
	self.roundManager = CombatRound:New()
	self.randomGenerator = nil
	self.battleLog = BattleLog:New()
	self.battleState = CombatState.BattleState.Idle
	self.battleResult = CombatState.BattleResult.None
	self.config = {}
	self.inputManager = CombatInput:New(CombatInput.InputMode.Auto, operate)
	self.isPaused = false
	self.currentActor = nil
	self:InitPlayers(players)
	Formula.CombatManager = self;

	print("[CombatSystem] Initialized, version:", BATTLE_VERSION)
end

function M:InitPlayers(players)
	if players == nil then
        return
    end
	for i, player in ipairs(players.player) do
		local entity = CombatEntity:New(player.id, player.position, CombatState.EntityType.Player, player.prop)
		entity:Initialize()
		self.roundManager:RegisterEntity(entity)
	end

	for i, enemy in ipairs(players.enemy) do
		local entity = CombatEntity:New(enemy.id, enemy.position, CombatState.EntityType.Enemy, enemy.prop)
		entity:Initialize()
		self.roundManager:RegisterEntity(entity)

	end
end

--- 反初始化战斗管理器
function M:Deinitialize()
	if self.roundManager then
		self.roundManager:Reset()
		self.roundManager = nil
	end
	if self.battleLog then
		self.battleLog:Clear()
		self.battleLog = nil
	end
	self.randomGenerator = nil
	self.battleState = CombatState.BattleState.Idle
	self.battleResult = CombatState.BattleResult.None
	self.config = {}
	Formula.CombatManager = nil
end

--- 执行单个回合的完整流程
---@param currentActor CombatEntity 当前行动实体
---@return boolean 是否成功执行回合（false表示暂停或结束）
function M:ExecuteSingleRound(currentActor)
	--- 开始新回合记录
	local currentRound = self.roundManager:GetCurrentRound()
	if currentRound == 0 then
		self.roundManager:StartNewRound()
		self:StartRoundLog(self.roundManager:GetCurrentRound())
	else
		self:StartRoundLog(self.roundManager:GetCurrentRound())
	end

	--- 步骤6: 角色回合开始阶段相关逻辑检测
	self:OnTurnStart(currentActor)

	--- 步骤7: 角色行动开始
	self:OnActionStart(currentActor)

	--- 步骤8: 角色行动开始阶段相关逻辑检测
	self:CheckActionStartPhase(currentActor)

	--- 步骤9: 角色开始攻击流程
	self:OnAttackStart(currentActor)

	--- 步骤10: 角色开始攻击阶段相关逻辑检测
	self:CheckAttackStartPhase(currentActor)

	--- 步骤11: 角色攻击生效
	self:OnAttackEffect(currentActor)

	--- 如果暂停，返回 false
	if self.isPaused then
		return false
	end

	--- 步骤12: 伤害生效前阶段相关逻辑检测
	self:CheckBeforeDamagePhase(currentActor)

	--- 步骤13: 造成伤害
	self:OnDealDamage(currentActor)

	--- 步骤14: 伤害生效后阶段相关逻辑检测
	self:CheckAfterDamagePhase(currentActor)

	--- 步骤15: 角色攻击完成
	self:OnAttackEnd(currentActor)

	--- 步骤16: 角色攻击完成阶段相关逻辑检测
	self:CheckAttackEndPhase(currentActor)

	--- 步骤17: 角色行动结束
	self:OnActionEnd(currentActor)

	--- 步骤18: 角色行动结束阶段相关逻辑检测
	self:CheckActionEndPhase(currentActor)

	--- 步骤19: 角色回合结束
	self:OnTurnEnd(currentActor)

	--- 步骤20: 角色回合结束阶段逻辑检测
	self:CheckTurnEndPhase(currentActor)

	--- 步骤22: 行动值计算
	self:CalculateActionValues()

	--- 输出当前回合战斗记录
	self:PrintCurrentRoundLog()
	self:EndRoundLog()

	return true
end

--- 主战斗循环（自动循环，用于 Verify 模式）
function M:RunBattleLoopAuto(endPlayCallback)
	while true do
		--- 步骤21: 战斗是否结束判断
		self.battleResult = self.roundManager:CheckBattleEnd()
		if self.battleResult ~= CombatState.BattleResult.None then
			if endPlayCallback then
				endPlayCallback(self.battleResult)
			end
			break
		end

		--- 步骤5: 进入角色回合
		local currentActor = self.roundManager:GetNextActor()
		if not currentActor then
			break
		end

		self.roundManager:SetCurrentActor(currentActor)

		--- 执行单个回合
		if not self:ExecuteSingleRound(currentActor) then
			break
		end
	end
end

--- 手动战斗循环（逐个回合生成，支持暂停等待）
function M:RunBattleLoopManual(endPlayCallback)
	--- 如果暂停，直接返回等待外部输入
	if self.isPaused then
		if self.inputManager:IsInputCompleted() then
			self.isPaused = false
			self.currentActor = nil
		end
		return
	end

	--- 步骤21: 战斗是否结束判断
	self.battleResult = self.roundManager:CheckBattleEnd()
	if self.battleResult ~= CombatState.BattleResult.None then
		if endPlayCallback then
			endPlayCallback(self.battleResult)
		end
		return
	end

	--- 步骤5: 进入角色回合
	local currentActor = self.roundManager:GetNextActor()
	if not currentActor then
		return
	end

	self.roundManager:SetCurrentActor(currentActor)

	--- 执行单个回合
	self:ExecuteSingleRound(currentActor)
end

--- 开始战斗流程
function M:StartBattle(endPlayCallback)
	print("[CombatManager] Start Battle ====================================")

	--- 步骤1: 战斗数据初始化
	self:SetBattleState(CombatState.BattleState.Initializing)
	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.BattleInitialize)
	eventData.battleState = self:GetBattleState()
	CombatEvent.Publish(CombatEvent.EventType.BattleInitialize, eventData)

	--- 步骤2: 战斗开始
	self:SetBattleState(CombatState.BattleState.InBattle)
	eventData = CombatEvent.CreateEventData(CombatEvent.EventType.BattleStart)
	eventData.battleState = self:GetBattleState()
	CombatEvent.Publish(CombatEvent.EventType.BattleStart, eventData)

	--- 步骤3: 开场技能检测
	self:CheckOpenSkill()

	--- 步骤4: 行动值计算
	self:CalculateActionValues()

	--- 根据输入模式选择战斗循环
	if self.inputManager:GetMode() == CombatInput.InputMode.Verify then
		--- Verify 模式：使用自动循环
		self:RunBattleLoopAuto(endPlayCallback)
	else
		--- Manual 和 Auto 模式：使用手动循环（逐个回合生成）
		self:RunBattleLoopManual(endPlayCallback)
	end
end

--- 检测开场技能
function M:CheckOpenSkill()
	print("[CombatManager] Step 3: Check Open Skill")

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.OpenSkillCheck)
	eventData.round = self.roundManager:GetCurrentRound()
	CombatEvent.Publish(CombatEvent.EventType.OpenSkillCheck, eventData)
end

--- 计算行动值
function M:CalculateActionValues()
	print("[CombatManager] Calculate Action Values")

	self.roundManager:CalculateActionValues()

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.ActionValueCalc)
	eventData.round = self.roundManager:GetCurrentRound()
	CombatEvent.Publish(CombatEvent.EventType.ActionValueCalc, eventData)
end

--- 角色回合开始
---@param actor CombatEntity
function M:OnTurnStart(actor)
	print("[CombatManager] Turn Start:", actor.name)

	self.battleState = CombatState.BattleState.TurnStart

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.TurnStart)
	eventData.currentActor = actor
	eventData.round = self.roundManager:GetCurrentRound()
	eventData.actionValue = actor.prop.actionValue:ToNumber()
	CombatEvent.Publish(CombatEvent.EventType.TurnStart, eventData)
end

--- 检测回合开始阶段
---@param actor CombatEntity
function M:CheckTurnStartPhase(actor)
	-- 可以在这里添加Buff触发、被动技能等逻辑
end

--- 角色行动开始
---@param actor CombatEntity
function M:OnActionStart(actor)
	print("[CombatManager] Action Start:", actor.name)

	self.battleState = CombatState.BattleState.ActionStart

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.ActionStart)
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.ActionStart, eventData)
end

--- 检测行动开始阶段
---@param actor CombatEntity
function M:CheckActionStartPhase(actor)
	-- 检测行动开始时的Buff、被动技能等
end

--- 角色开始攻击流程
---@param actor CombatEntity
function M:OnAttackStart(actor)
	print("[CombatManager] Attack Start:", actor.name)

	self.battleState = CombatState.BattleState.Attacking

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.AttackStart)
	eventData.attacker = actor
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.AttackStart, eventData)

end

--- 检测攻击开始阶段
---@param actor CombatEntity
function M:CheckAttackStartPhase(actor)
	-- 检测攻击开始时的Buff、被动技能等
end

--- 角色攻击生效
---@param actor CombatEntity
function M:OnAttackEffect(actor)
	print("[CombatManager] Attack Effect:", actor.name)

	self.battleState = CombatState.BattleState.Attacking

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.AttackEffect)
	eventData.attacker = actor
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.AttackEffect, eventData)

	--- 如果是手动模式，暂停并等待外部输入
	if self.inputManager:GetMode() == CombatInput.InputMode.Manual then
		print("[CombatManager] Paused, waiting for manual input...")
		self.isPaused = true
		self.currentActor = actor
		return
	end

	--- 自动或验证模式：立即获取输入数据并执行
	local roundIndex = self.roundManager:GetCurrentRound()
	local inputData = self.inputManager:GetInputData(roundIndex, actor)

	if inputData and #inputData >= 2 then
		local skillId = inputData[1]
		local targetIds = inputData[2]

		--- 执行伤害计算和应用
		self:OnDealDamage(actor, skillId, targetIds)
	else
		print("[CombatManager] Warning: Invalid input data from CombatInput")
	end
end

--- 检测伤害生效前阶段
---@param actor CombatEntity
function M:CheckBeforeDamagePhase(actor)
	print("[CombatManager] Before Damage Phase:", actor.name)

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.BeforeDamage)
	eventData.attacker = actor
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.BeforeDamage, eventData)
end

--- 造成伤害
---@param actor CombatEntity
---@param skillId number 技能ID
---@param targetIds table 目标ID列表
function M:OnDealDamage(actor, skillId, targetIds)
	print("[CombatManager] Deal Damage:", actor.name)

	self.battleState = CombatState.BattleState.DamageCalc

	-- 获取技能
	local skill = actor:GetSkill(skillId)
	if not skill then
		print("[CombatManager] Warning: Skill not found:", skillId)
		return
	end

	-- 获取目标
	local targets = self:GetAttackTargets(targetIds)
	if not targets or #targets == 0 then
		print("[CombatManager] Warning: No valid targets found")
		return
	end

	local damages = {}
	local weakness = {}

	for _, target in ipairs(targets) do
		if target:IsAlive() then
			-- 计算伤害（包含暴击判定）
			local damage, isCritical = Formula:CalcDamage(actor, target, skill)

			-- 应用伤害
			target:TakeDamage(damage)

			-- 记录战斗数据
			table.insert(damages, -damage:ToNumber())
			table.insert(weakness, -1) -- 默认弱点值

			-- 发布伤害事件
			local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.DealDamage)
			eventData.attacker = actor
			eventData.defender = target
			eventData.damage = damage:ToNumber()
			eventData.isCritical = isCritical
			eventData.currentActor = actor
			CombatEvent.Publish(CombatEvent.EventType.DealDamage, eventData)

			print("[CombatManager]", actor.name, "deals", damage:ToNumber(), "damage to", target.name, isCritical and "(CRITICAL!)" or "")
		end
	end

	-- 记录技能行动到战斗日志
	if #targetIds > 0 then
		self:LogSkillAction(actor.id, skillId, targetIds, damages, weakness)
	end
end

--- 检测伤害生效后阶段
---@param actor CombatEntity
function M:CheckAfterDamagePhase(actor)
	print("[CombatManager] After Damage Phase:", actor.name)

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.AfterDamage)
	eventData.attacker = actor
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.AfterDamage, eventData)
end

--- 角色攻击完成
---@param actor CombatEntity
function M:OnAttackEnd(actor)
	print("[CombatManager] Attack End:", actor.name)

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.AttackEnd)
	eventData.attacker = actor
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.AttackEnd, eventData)
end

--- 检测攻击完成阶段
---@param actor CombatEntity
function M:CheckAttackEndPhase(actor)
	-- 检测攻击完成时的Buff、被动技能等
end

--- 角色行动结束
---@param actor CombatEntity
function M:OnActionEnd(actor)
	print("[CombatManager] Action End:", actor.name)

	self.battleState = CombatState.BattleState.ActionEnd

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.ActionEnd)
	eventData.currentActor = actor
	CombatEvent.Publish(CombatEvent.EventType.ActionEnd, eventData)
end

--- 检测行动结束阶段
---@param actor CombatEntity
function M:CheckActionEndPhase(actor)
	-- 检测行动结束时的Buff、被动技能等
	-- 减少Buff持续时间
	actor:DecrementBuffDuration()
end

--- 角色回合结束
---@param actor CombatEntity
function M:OnTurnEnd(actor)
	print("[CombatManager] Turn End:", actor.name)

	self.battleState = CombatState.BattleState.TurnEnd

	local eventData = CombatEvent.CreateEventData(CombatEvent.EventType.TurnEnd)
	eventData.currentActor = actor
	eventData.round = self.roundManager:GetCurrentRound()
	CombatEvent.Publish(CombatEvent.EventType.TurnEnd, eventData)
end

--- 检测回合结束阶段
---@param actor CombatEntity
function M:CheckTurnEndPhase(actor)
	-- 检测回合结束时的Buff、被动技能等
	for _, entity in pairs(self.roundManager:GetAllEntities()) do
		entity:DecrementBuffDuration()
	end
end

--- 获取攻击目标
---@param targetIds CombatEntity
---@return table
function M:GetAttackTargets(targetIds)
	local ret = {}
	for _, targetId in pairs(targetIds) do
		local target = self:GetEntityById(targetId)
		if target then
			table.insert(ret, target)
		end
	end
	return ret
end

--- 获取所有存活的实体
---@return table
function M:GetAllAliveEntities()
	return self.roundManager:GetAllEntities()
end

--- 随机数接口
function M:Random()
	return self.randomGenerator:Next()
end

function M:RandomFloat()
	return self.randomGenerator:NextFloat()
end

function M:RandomFixed()
	return self.randomGenerator:NextFixed()
end

function M:RandomRange(min, max)
	return self.randomGenerator:NextRange(min, max)
end

function M:RandomRangeFixed(min, max)
	return self.randomGenerator:NextRangeFixed(min, max)
end

function M:RandomRangeFloat(min, max)
	return self.randomGenerator:NextRangeFloat(min, max)
end

function M:Choice(array)
	return self.randomGenerator:Choice(array)
end

--- 获取当前战斗状态
---@return number
function M:GetBattleState()
	return self.battleState
end

--- 设置战斗状态
---@param state number
function M:SetBattleState(state)
	self.battleState = state
end

--- 获取回合管理器
---@return CombatRound
function M:GetRoundManager()
	return self.roundManager
end

--- 获取战斗结果
---@return number
function M:GetBattleResult()
	return self.battleResult
end

--- 添加技能到实体
---@param entityId number 实体ID
---@param skillData table 技能数据
function M:AddSkillToEntity(entityId, skillData)
	local entity = self:GetEntityById(entityId)
	if entity then
		local skill = Skill:New(skillData)
		entity:AddSkill(skillData.id, skill)
		print("[CombatManager] Added skill", skillData.id, "to entity", entityId)
	else
		print("[CombatManager] Failed to add skill - entity not found:", entityId)
	end
end

--- 添加Buff到实体
---@param entityId number 实体ID
---@param buffData table Buff数据
function M:AddBuffToEntity(entityId, buffData)
	local entity = self:GetEntityById(entityId)
	if entity then
		local buff = Buff:New(buffData)
		entity:AddBuff(buffData.id, buff)

		--- 记录Buff行动到战斗日志
		self.battleLog:LogBuffAction(entityId, buffData.id, buffData.effectType or "none", buffData.effectValue or 0)

		print("[CombatManager] Added buff", buffData.id, "to entity", entityId)
	else
		print("[CombatManager] Failed to add buff - entity not found:", entityId)
	end
end

--- 根据ID获取实体
---@param entityId number 实体ID
---@return CombatEntity|nil
function M:GetEntityById(entityId)
	if not self.roundManager then
		return nil
	end

	local allEntities = self.roundManager:GetAllEntities()
	for _, entity in ipairs(allEntities) do
		if entity.id == entityId then
			return entity
		end
	end
	return nil
end

--- 获取实体的技能
---@param entityId number 实体ID
---@param skillId number 技能ID
---@return Skill|nil
function M:GetEntitySkill(entityId, skillId)
	local entity = self:GetEntityById(entityId)
	if entity then
		return entity:GetSkill(skillId)
	end
	return nil
end

--- 获取实体的所有技能
---@param entityId number 实体ID
---@return table
function M:GetEntityAllSkills(entityId)
	local entity = self:GetEntityById(entityId)
	if entity then
		return entity:GetAllSkills()
	end
	return {}
end

--- 获取实体的Buff
---@param entityId number 实体ID
---@param buffId number BuffID
---@return Buff|nil
function M:GetEntityBuff(entityId, buffId)
	local entity = self:GetEntityById(entityId)
	if entity and entity.buffs then
		return entity.buffs[buffId]
	end
	return nil
end

--- 移除实体的Buff
---@param entityId number 实体ID
---@param buffId number BuffID
function M:RemoveEntityBuff(entityId, buffId)
	local entity = self:GetEntityById(entityId)
	if entity then
		entity:RemoveBuff(buffId)
		print("[CombatManager] Removed buff", buffId, "from entity", entityId)
	end
end

--- 战斗记录相关方法

--- 开始新回合记录
---@param roundIndex number 回合索引
function M:StartRoundLog(roundIndex)
	self.battleLog:StartRound(roundIndex)
end

--- 结束当前回合记录
function M:EndRoundLog()
	self.battleLog:EndRound()
end

--- 记录技能行动
---@param attackerId number 攻击者ID
---@param skillId number 技能ID
---@param targetIds table 目标ID列表
---@param damages table 伤害列表
---@param weakness table 弱点列表
function M:LogSkillAction(attackerId, skillId, targetIds, damages, weakness)
	self.battleLog:LogSkillAction(attackerId, skillId, targetIds, damages, weakness)
end

--- 记录Buff行动
---@param targetId number 目标ID
---@param buffId number BuffID
---@param effectType string 效果类型
---@param effectValue number 效果值
function M:LogBuffAction(targetId, buffId, effectType, effectValue)
	self.battleLog:LogBuffAction(targetId, buffId, effectType, effectValue)
end

--- 输出当前回合战斗记录
function M:PrintCurrentRoundLog()
	self.battleLog:PrintCurrentRoundLog()
end

--- 输出所有回合战斗记录
function M:PrintAllRoundLogs()
	self.battleLog:PrintAllRoundLogs()
end

--- 获取当前回合日志
---@return table
function M:GetCurrentRoundLog()
	return self.battleLog:GetCurrentRoundLog()
end

--- 获取所有回合日志
---@return table
function M:GetAllRoundLogs()
	return self.battleLog:GetAllRoundLogs()
end

--- 获取指定回合日志
---@param roundIndex number 回合索引
---@return table|nil
function M:GetRoundLog(roundIndex)
	return self.battleLog:GetRoundLog(roundIndex)
end

--- 获取战斗日志对象
---@return BattleLog
function M:GetBattleLog()
	return self.battleLog
end

return M