---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created liujinchun.ljc
--- DateTime: 2026/03/02 14:03
---

local Fix = require("lfixed")

--- 创建不可修改的常量表
local function createReadonlyTable(t)
    local metatable = {
        __index = t,
        __newindex = function(_, key, value)
            error("[CombatConst] Attempt to modify constant '" .. tostring(key) .. "' with value " .. tostring(value), 2)
        end,
        __metatable = false -- 防止获取或修改元表
    }
    return setmetatable({}, metatable)
end

--- 原表：定义所有常量
local M = {
    zero = Fix.new(0),
    minCritDamage = Fix.new(1.5)
}

--- 返回只读的常量表
return createReadonlyTable(M)