---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/27
---


---@class Formula
local Fix = require("lfixed")

local CombatConst = require("GamePlay.Combat.GameLogic.CombatConst")
local M = {}
-- 战斗管理器 初始化战斗的时候设置一下
M.CombatManager = nil
-- 计算伤害
---@param attacker CombatEntity 攻击者
---@param target CombatEntity 目标
---@return fixed 伤害值
function M.CalcDamageDamage(attacker, target)
	return attacker.prop.damage
end

--- 计算防御
---@param attacker CombatEntity 攻击者
---@param target CombatEntity 目标
---@return fixed 防御值

function M.CalcDefense(attacker, target)
	return attacker.prop.defender
end

--- 范围函数
---@param value number 值
---@param min number 最小值
---@param max number 最大值
---@return number
function M.Range(value, min, max)
	if value < min then
		return min
	elseif value > max then
		return max
	else
		return value
	end
end

--- 随机数函数，使用 CombatSystem 的 randomGenerator 保证随机一致性
---@param min number 最小值
---@param max number 最大值
---@return number
function M.Random(min, max)
	if min == nil or max == nil then
		return M.CombatManager.RandomFloat()
	end
	return M.CombatManager.RandomRangeFloat(0, max)
end

--- 计算暴击率
---@param attacker CombatEntity 攻击者
---@param target CombatEntity 目标
---@return boolean

function M.CalcCritRate(attacker, target)
	local crit = attacker.prop.critAttack - target.prop.critDefense
	crit = M:Range(crit, 20, 80)
	local critRate = M.CalcCritRate(attacker, target)
	return critRate > M.Random(0, 10000)
end

--- 计算暴击伤害
---@param attacker CombatEntity 攻击者
---@param target CombatEntity 目标
---@return number
function M.CalcCritDamage(attacker, target)
	local baseCritDamage = attacker.prop.critDamage or CombatConst.minCritDamage
	return baseCritDamage
end

--- 计算伤害
---@param attacker CombatEntity 攻击者
---@param defender CombatEntity 目标
---@param skill Skill 技能
---@return number
function M:CalcDamage(attacker, defender, skill)
	attacker:CalcProp()
	defender:CalcProp()

	local isCrit = M.CalcCritRate(attacker, defender)
	local damage = skill:CalcDamage(attacker, defender)

	return damage
end

return M