
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/28
---

local LuaHelper = require("Utility.LuaHelper")
local CombatState = require("GamePlay.Combat.GameLogic.CombatState")
local BufferFactory = require("GamePlay.Combat.GameLogic.BufferFactory")
local Fix = require("lfixed")

---@class Skill
local M = LuaHelper.LuaClass()

function M:__OnNew(skillData)
    self.id = skillData.id or 0
    self.name = skillData.name or "UnknownSkill"
    self.skillType = skillData.skillType or CombatState.ActionType.Skill
	self.autoSkillType = skillData.autoSkillType
    self.damageMultiplier = Fix.new(skillData.damageMultiplier or 1.0)
    self.targetType = skillData.targetType or "single" -- single, multiple, all
    self.coolDown = skillData.coolDown or 0
    self.currentCoolDown = 0
    self.mpCost = skillData.mpCost or 0
    self.description = skillData.description or ""
end

--- 计算技能伤害
---@param attacker CombatEntity 攻击者
---@param target CombatEntity 目标
---@return lfixed 伤害值
function M:CalcDamage(attacker, target)
    local baseDamage = attacker.prop.attack * self.damageMultiplier
    local defense = target.prop.defense
    local damage = baseDamage - defense
    if damage < Fix.new(0) then
        damage = Fix.new(0)
    end
    return damage
end

--- 获取技能类型
--- @return 
---
function M:AutoSkillType()
	return self.autoSkillType
end

--- 检查技能是否可用
---@param attacker CombatEntity 攻击者
---@return boolean
function M:IsAvailable(attacker)
    if self.currentCoolDown > 0 then
        return false
    end
    -- 可以添加其他条件检查，如MP消耗等
    return true
end

--- 减少冷却时间
function M:DecrementCoolDown()
    if self.currentCoolDown > 0 then
        self.currentCoolDown = self.currentCoolDown - 1
    end
end

--- 使用技能
---@param attacker CombatEntity 攻击者
function M:UseSkill(attacker)
    if self.coolDown > 0 then
        self.currentCoolDown = self.coolDown
    end
end

function M:ApplyBufferEffect(attacker,target)
	-- 普通技能特有效果
	-- 添加Buff
	for i,v in pairs(self.Buffer) do
		local buffer = BufferFactory:Make(self.Buffer[i])
		if buffer.targetType == CombatState.BuffTargetType.Self then
			target:AddBuff(buffer)
		elseif buffer.targetType == CombatState.BuffTargetType.Target then
			attacker:AddBuff(buffer)
		elseif buffer.targetType == CombatState.BuffTargetType.SelfTeam  then
			local entities = attacker:BattleManager():GetAttackTargets(targets)
			for _, entity in pairs(entities) do
				entity:AddBuff(buffer)
			end
		elseif buffer.targetType == CombatState.BuffTargetType.TargetTeam then
			local entities = attacker:BattleManager():GetAttackTargets(attacker)
			for _, entity in pairs(entities) do
				entity:AddBuff(buffer)
			end
		end
	end
end

return M
