
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/28
---


local NormalSkill = require("Script/GamePlay/Combat/GameLogic/Skill/NormalSkill")
--- 构造函数
function M:__OnNew()
	self.skillMap = {}
	self:RegisterSkill(1, NormalSkill)
end

--- 创建技能实例
function M:Make(skillData)
	-- 参数验证
	-- 查找技能类
	-- 创建实例
	-- 返回结果
end

--- 注册新的技能类型
function M:RegisterSkill(skillId, skillClass)
	self.skillMap[skillId] = skillClass
end

--- 获取已注册的技能类型数量
function M:GetRegisteredSkillCount()
	-- 统计注册数量
end

--- 检查技能是否已注册
function M:IsSkillRegistered(skillId)
	return self.skillMap[skillId] ~= nil
end