---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/20 11:14
---
local LuaHelper = require("Utility.LuaHelper")

---@class LockController : UIControllerBase
local M = LuaHelper.LuaClass("UI.UIControllerBase")

function M:__OnNew(name, view, model, message)
	self.Super.__OnNew(self, name, view, model)
	self.view:SetTips(message)
end

---@param message string
function M:SetTips(message)
	if self.view then
		self.view:SetTips(message)
	end
end

return M