---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/2/2 14:55
---

---@type EventDispatcher
local EventDispatcher = require("Core.EventDispatcher")

---@type LuaHelper
local LuaHelper = require("Utility.LuaHelper")

---@type EventLoop
local EventLoop = require("Core.EventLoop")

local function RegisterEvent(name, callback)
	EventDispatcher.AddEvent(name,function(...)
		local param = table.pack(...)
		EventLoop.Timeout(1000,function()
			callback(table.unpack(param))
		end)
	end)
end

---Home
local function EnterHomeEditMode()
	local enterHomeEditMode = {
		furnitureBag = {
			{
				furnitureId = 1,
				count = 1,
			},
		},
	}
	EventDispatcher.Dispatch("ACEnterHomeEditMode",enterHomeEditMode)
end

local function LeaveHomeEditMode(furnitureBag, placement)
	local leaveHomeEditMode = {
		code = 1,
	}
	EventDispatcher.Dispatch("ACLeaveHomeEditMode",leaveHomeEditMode)
end

local function LeaveHome()
	EventDispatcher.RemoveEvent("CAEnterHomeEditMode")
	EventDispatcher.RemoveEvent("CALeaveHomeEditMode")
	EventDispatcher.RemoveEvent("CALeaveHome")
	local leaveHome = {
		code = 1,
	}
	EventDispatcher.Dispatch("ACEnterHome",leaveHome)
end


local function EnterHome()
	RegisterEvent("CALeaveHome",LeaveHome)
	RegisterEvent("CAEnterHomeEditMode",EnterHomeEditMode)
	RegisterEvent("CALeaveHomeEditMode",LeaveHomeEditMode)


	local enterHome = {
		placementList = {
			{
				furnitureId = 1,
				position = {
					x = 1,
					y = 1,
					z = 1,
				},
				rotationZ = 0
			},
			{
				furnitureId = 2,
				position = {
					x = 15,
					y = 1,
					z = 1,
				},
				rotationZ = 0
			},
		},
	}
	EventDispatcher.Dispatch("ACEnterHome",enterHome)
end

local function FinishCombat(data)
	EventDispatcher.RemoveEvent("CAFinishCombat")

	local finishCombat = {
		code = 1,
	}
	EventDispatcher.Dispatch("ACFinishCombat",finishCombat)
end

---Combat
local function EnterCombat()
	RegisterEvent("CAFinishCombat",FinishCombat)
	
	EventDispatcher.Dispatch("ACEnterCombat")
end

---@class SimulationServer
local M = {}

function M.Initialize()
---Home
	RegisterEvent("CAEnterHome",EnterHome)

---Combat
    RegisterEvent("CAEnterCombat",EnterCombat)
	
end

function M.Shutdown()
    EventDispatcher.RemoveEvent("CAEnterHome")
    EventDispatcher.RemoveEvent("CAEnterCombat")
end

return M