---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/2/2 10:21
---


local LuaHelper = require("Utility.LuaHelper")
local UEHelper = require("Core.UEHelper")
local UIManager = require("UI.UIManager")

---@class TestMainController : UIControllerBase
local M = LuaHelper.LuaClass("UI.UIControllerBase")


function M:__OnNew(name, view, model)
	self.Super.__OnNew(self, name, view, model)
	self.view:SubscribeEvent("OnUIExample", self.OnUIExample, self)
	self.view:SubscribeEvent("OnRunLuaTestCase", self.OnRunLuaTestCase, self)
	self.view:SubscribeEvent("OnClose", self.OnClose, self)
end

function M:OnUIExample()
	UE.UGameplayStatics.OpenLevel(UEHelper.GetGameInstance(),"/Game/Test/UIExample/l_UIMap")
end

function M:OnRunLuaTestCase()
	print("OnRunLuaTestCase")
end

function M:OnClose()
	UIManager.State_CloseAndReopen()
end

return M