---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/28
---

local LuaHelper = require("Utility.LuaHelper")
local Fix = require("lfixed")

---@class NormalSkill
local M = LuaHelper.LuaClass("GamePlay.Combat.GameLogic.Skill")

function M:__OnNew(skillData)
    -- 调用基类构造函数
    self.Super.__OnNew(self,skillData)
    
    -- 普通技能特有属性
    self.baseDamage = Fix.new(skillData.baseDamage or 0)
    self.attackPercent = Fix.new(skillData.attackPercent or 1.0)
    self.defensePercent = Fix.new(skillData.defensePercent or 0)
    self.critBonus = Fix.new(skillData.critBonus or 0)
	self.Buffer = skillData.Buffer
end

--- 计算技能伤害
---@param attacker CombatEntity 攻击者
---@param target CombatEntity 目标
---@return fixed 伤害值
function M:CalcDamage(attacker, target)
    local damage = 0
	return damage
end

return M