---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/20 11:14
---
local LuaHelper = require("Utility.LuaHelper")
local EventLoop = require("Core.EventLoop")
local UIManager = require("UI.UIManager")

---@class ToastController : UIControllerBase
local M = LuaHelper.LuaClass("UI.UIControllerBase")

function M:__OnNew(name, view, model, content, duration)
    self.Super.__OnNew(self, name, view, model)
	self.view:SetContent(content)

	self.autoCloseTimer = EventLoop.Timeout(duration * 1000, function()
		self.autoCloseTimer = nil
		UIManager.Toast_Close(self.name)
	end, false)
end

function M:Destroy()
    if self.autoCloseTimer then
        self.autoCloseTimer:stop()
        self.autoCloseTimer = nil
    end
    self.Super.Destroy(self)
end

function M:UpdateToastPosition(positionY)
    return self.view:UpdateToastPosition(positionY)
end

return M