---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/24 11:55
---
----@type ltw2_event
local levent = require("ltw2.event")

---@class Channel
local M = {}

---@param addr string
---@param timeoutMs integer
---@param bStream boolean
---@param func function(bSucc:boolean)
---@return Channel
function M.Connect(addr, timeoutMs, bStream, func)
	local conn = levent.connection_new()
	local self = {
        conn = conn,
		bConnecting = true
    }
	
	local rc = conn:connect(bStream,addr,function(bSucc)  
		if self.bConnecting then
            self.bConnecting = false
			if self.timeout then
                self.timeout:stop()
                self.timeout = nil
            end
			func(true)
        end
	end)
	
	if not rc then
        return nil
    end
	
	if timeoutMs and timeoutMs > 0 then
        self.timeout = levent.timer_watcher_new()
        self.timeout:start(timeoutMs,true, function()
			if self.bConnecting then
				self.bConnecting = false
				self.timeout = nil
				if self.conn then
					self.conn:close(true)
					self.conn = nil
				end
				func(false)
			end
		end)
    end
	
    return setmetatable(self,{__index = M})
end

---@param func function()
function M.SetDisconnectCallback(self,func)
	self.disconnectCB = func
end

---@param func function(data:string)
function M.SetMessageCallback(self,func)
    self.messageCB = func
end

---@param bKeepAlive boolean
---@param bTcpNoDelay boolean
---@return boolean
function M.Bind(self, bKeepAlive, bTcpNoDelay)
	local conn = self.conn
	if not conn then
		return false
	end
		
	conn:set_disconnect_callback(function()
		if self.disconnectCB then
			self.disconnectCB()
			self.disconnectCB = nil
		end
	end)
	
	conn:set_close_callback(function()
		self.conn = nil
    end)
	
	conn:set_receive_callback(function(data)
		if self.messageCB then
            self.messageCB(data)
        end
    end)

	return conn:bind(bKeepAlive, bTcpNoDelay)
end

---@param data string
---@return boolean
function M.Send(self,data)
    local conn = self.conn
    if not conn then
        return false
    end
    return conn:send(data)
end

---@param timeoutMs integer
function M.Close(self,timeoutMs)
	if self.bConnecting then
		self.bConnecting = false

		if self.timeout then
			self.timeout:stop()
			self.timeout = nil
		end

		if self.conn then
			self.conn:close(true)
			self.conn = nil
		end
	else
		if self.conn then
			if timeoutMs and timeoutMs > 0 then
				self.timeout = levent.timer_watcher_new()
                self.timeout:start(timeoutMs,true, function()
					self.timeout = nil
					if self.conn then
                        self.conn:close(true)
                        self.conn = nil
                    end
                end)
				self.conn:close()
            else
                self.conn:close(true)
				self.conn = nil
            end
		end
	end
end

return M