---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 18:54
---

---@type lproject
local lproject = require("lproject")

----@type ltw2_core
local lcore = require("ltw2.core")

----@type ltw2_event
local levent = require("ltw2.event")

local LuaHelper = require("Utility.luaHelper")

local tickerList = {}

local timerList = {}

local function Tick(deltaTime)
	levent.run()
	for obj, func in pairs(tickerList) do
		LuaHelper.XpCall(func, obj, deltaTime * 1000)
	end
end

local function ReceiveBeginPlay()
	assert(levent.start(1), "levent.start failed")
end

local function ReceiveEndPlay()
	-- 安全地停止所有 timer
	for timer in pairs(timerList) do
		-- 使用 pcall 保护调用，避免访问已释放的对象导致崩溃
		pcall(function()
			if timer then
				timer:stop()
			end
		end)
    end
	timerList = {}
	
	-- 安全地停止事件循环
	pcall(function()
		levent.stop()
	end)
end

--lproject.set_beginplay_callback(ReceiveBeginPlay)
--
--lproject.set_tick_callback(Tick)
--
--lproject.set_endplay_callback(ReceiveEndPlay)

---@class EventLoop
local M = {}

---@return boolean
function M.Startup()
	return lproject.startup()
end

---@return boolean
function M.Shutdown()
	return lproject.shutdown()
end
---@param obj any
---@param func function
function M.AddTicker(obj, func)
	tickerList[obj] = func
end

---@param obj any
function M.DelTicker(obj)
	tickerList[obj] = nil
end

function M.ResetTicker()
	tickerList = {}
end

---@return integer
function M.ClockMonotonic()
	return lcore.clock_monotonic()
end

---@return integer
function M.ClockRealtime()
	return lcore.clock_realtime()
end

---@param duration integer
function M.SleepFor(duration)
	lcore.sleep_for(duration)
end

---@param intervalMs integer
---@param func function
---@return ltw2_event_timer_watcher
function M.Timeout(intervalMs, func, bLoop)
	local timer = levent.timer_watcher_new()
	-- 检查 timer 是否创建成功
	if not timer then
		return nil
	end
	
	if not timer:start(intervalMs, not bLoop, function()
		func()
		if not bLoop then
			timerList[timer] = nil
		end
	end) then
        return nil
    end
	timerList[timer] = timer
	return timer
end

return M