---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 17:49
---

local TableEx = require "Utility.TableEx"
local LuaHelper = require "Utility.LuaHelper"

---@class EventDispatcher
local M = {}

local eventMap = {}
local weak = { __mode = "kv" }

---@param event string
---@param func function(target:table, ...:any)
---@param target table
function M.AddEvent(event, func, target)
	assert(event and type(event) == "string", "event is not a string")
	assert(func and type(func) == "function", "func is not a function")
	local listener = eventMap[event] or {}
	local obj = target or weak
	local v = { func, obj }
	setmetatable(v, weak)
	table.insert(listener, v)
	eventMap[event] = listener
end

---@param event string
---@param func function(target:table, ...:any)
function M.RemoveEvent(event, func)
	assert(event and type(event) == "string", "event is not a string")
	
	local listener = eventMap[event]
	if not listener then
		return
	end

	if not func then
		eventMap[event] = nil
		return
	end

	TableEx.ArrayRemove(listener, function(v)
		if v[1] == func then
			return true
		end
	end)
end

---@param event string
---@vararg any
function M.Dispatch(event, ...)
	assert(event and type(event) == "string", "event is not a string")
	local listener = eventMap[event]
	if listener then
		for _, v in ipairs(listener) do
			if v[2] == weak then
				LuaHelper.XpCall(v[1], ...)
			else
				LuaHelper.XpCall(v[1], v[2], ...)
			end
		end
	end
end

return M