---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 17:49
---

local TableEx = require "Utility.TableEx"
local LuaHelper = require "Utility.LuaHelper"

---@class EventDispatcher
local M = {}

local eventMap = {}

---@param event string
---@param target any
---@param func function(target:any, ...:any)
function M.AddEventListener(event, target, func)
	local listener = eventMap[event] or {}
	local obj = target or weak
	local v = { func, obj }
	setmetatable(v, weak)
	table.insert(listener, v)
	eventMap[event] = listener
end

---@param event string
---@param target any
function M.RemoveEventListener(event, target)
	local listener = eventMap[event]
	if not listener then
		return
	end

	if not target then
		eventMap[event] = nil
		return
	end

	TableEx.ArrayRemoveValue(listener, function(v)
		if v[2] == target then
			return true
		end
	end)
end

---@param event string
---@vararg any
function M.DispatchEvent(event, ...)
	local listener = eventMap[event]
	if listener then
		for _, v in ipairs(listener) do
			if v[2] == weak then
				LuaHelper.XpCall(v[1], ...)
			else
				LuaHelper.XpCall(v[1], v[2], ...)
			end
		end
	end
end

return M