---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 19:26
---

local limitMaxHttpRequest<const> = 15
local httpRequestNum = 0
local httpRequestQueue = {}

---@class HttpHelper
local M = {}

---@param url string
---@param target table
---@param func function
---@param verb EHttpVerb
---@param contentType EHttpContentType
---@param context string
---@param token string
function M.Request(url, target, func, verb, contentType, context, token)
	assert(target and type(target) == "table", "httpObj is not a table")
	assert(func and type(func) == "function", "func is not a function")
	
	local httpObj = UE.UHttpObject.HttpAsyncAction(url, verb, contentType, context, token)
	httpObj:RegisterCompleteCallback(function(result, code)
		if target then
			func(target, result, code)
		else
			func(result, code)
		end
		httpRequestNum = httpRequestNum - 1
        if httpRequestNum <= limitMaxHttpRequest and #httpRequestQueue > 0 then
            local requestObj = httpRequestQueue[1]
			requestObj:Request()
            table.remove(httpRequestQueue, 1)
        end	
	end)
	
	if httpRequestNum <= limitMaxHttpRequest then
		httpObj:Request()
		httpRequestNum = httpRequestNum + 1
	else
		httpRequestQueue[#httpRequestQueue + 1] = httpObj
	end
end

---@param url string
---@param target table
---@param func function
---@param savePath string
function M.Download(url, target, func,savePath)
    assert(target and type(target) == "table", "httpObj is not a table")
    assert(func and type(func) == "function", "func is not a function")
    
    local httpObj = UE.UHttpDownloadObject.HttpAsyncAction(url, UE.EHttpVerb.GET, UE.EHttpContentType.None, "","", savePath)
	httpObj:RegisterCompleteCallback(function(result, code)
		if target then
			func(target, result, code)
		else
			func(result, code)
		end
		httpRequestNum = httpRequestNum - 1
		if httpRequestNum <= limitMaxHttpRequest and #httpRequestQueue > 0 then
			local requestObj = httpRequestQueue[1]
			requestObj:Request()
			table.remove(httpRequestQueue, 1)
		end
	end)
	
	if httpRequestNum <= limitMaxHttpRequest then
        httpObj:Request()
        httpRequestNum = httpRequestNum + 1
    else
        httpRequestQueue[#httpRequestQueue + 1] = httpObj
    end
end

---@param url string
---@param target table
---@param func function
---@param filePath string
function M.Upload(url, target, func, filePath)
	assert(target and type(target) == "table", "httpObj is not a table")
	assert(func and type(func) == "function", "func is not a function")

	local httpObj = UE.UHttpUploadObject.HttpAsyncAction(url, UE.EHttpVerb.Post, UE.EHttpContentType.Form_Data, "","", filePath)
	httpObj:RegisterCompleteCallback(function(result, code)
		if target then
			func(target, result, code)
		else
			func(result, code)
		end
		httpRequestNum = httpRequestNum - 1
		if httpRequestNum <= limitMaxHttpRequest and #httpRequestQueue > 0 then
			local requestObj = httpRequestQueue[1]
			requestObj:Request()
			table.remove(httpRequestQueue, 1)
		end
	end)

	if httpRequestNum <= limitMaxHttpRequest then
		httpObj:Request()
		httpRequestNum = httpRequestNum + 1
	else
		httpRequestQueue[#httpRequestQueue + 1] = httpObj
	end
end

return M