---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/17 10:13
---

local LuaHelper = require("Utility.LuaHelper")
local Observable = require("Core.Observable")

---@class ModelBase
local M = LuaHelper.LuaClass()

function M:__OnNew()
	self.subject = Observable()
end

function M:__OnGC()
	if self.subject then
		self.subject:RemoveAll()
		self.subject = nil
	end
end

--- @param signal string
--- @param func function(...:any)
--- @param observer table @[optional]
function M:SubscribeEvent(signal, func, observer)
	self.subject:Register(signal, func, observer)
end

--- @param signal string
function M:UnsubscribeEvent(signal)
	self.subject:Deregister(signal)
end

--- @param signal string
function M:CreateEvent(signal)
	return function(...)
		self:TriggerEvent(signal, ...)
	end
end

function M:RemoveAllEvent()
    self.subject:RemoveAll()
end

--- @param observer table
function M:RemoveObserverEvent(observer)
	self.subject:RemoveObserver(observer)
end

--- @param signal string
--- @vararg any
function M:TriggerEvent(signal, ...)
	self.subject:Notify(signal, ...)
end

return M
