---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/18 11:47
---

local LuaHelper = require("Utility.LuaHelper")
local Interface = require("Utility.Interface")

---@class MultiDelegate
local M = Interface("MultiDelegate")

function M:__init()
    self.listenerSet = {}
	self.listenerList = {}
end

---@param func function(...:any)
---@return boolean
function M:Add(func)
	assert(func and type(func) == "function", "func is not a function")
	if  self.listenerSet[func] then
		return false
	end

	self.listenerSet[func] = true
	table.insert(self.listenerList, func)
	return true
end

---@param obj table
---@param method function(...:any)
---@return boolean
function M:AddObject(obj,method)
	assert(obj and type(obj) == "table", "obj is not a table")
	assert(method and type(method) == "function", "method is not a function")
	if  self.listenerSet[method] then
		return false
	end

	self.listenerSet[method] = true
	local func = LuaHelper.Handler(obj, method)
	table.insert(self.listenerList, func)
	return true
end

---@param func function(...:any)
---@return boolean
function M:Remove(func)
    assert(func and type(func) == "function", "func is not a function")
	if not self.listenerSet[func] then
		return false
    end
    self.listenerSet[func] = nil

    for k,v in ipairs(self.listenerList) do
        if v == func then
            table.remove(self.listenerList, k)
            break
        end
    end
	
	return true
end

function M:RemoveAll()
	self.listenerSet = {}
    self.listenerList = {}
end

---@vararg any
---@return boolean
function M:Broadcast(...)
	if #self.listenerList == 0 then
        return false
    end
	
	local snapshot = {}
	for i = 1, #self.listenerList do
		snapshot[i] = self.listenerList[i]
	end
	
	for _,func in ipairs(snapshot) do
		func(...)
	end
	return true
end

return M