---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/18 11:47
---

local LuaHelper = require("Utility.LuaHelper")
local Interface = require("Utility.Interface")
local TableEx = require("Utility.TableEx")

local weak = { __mode = "kv" }

---@class MultiDelegate
local M = Interface("MultiDelegate")

function M:__init()
    self.listenerSet = {}
	self.listenerList = {}
end

---@param func function(...:any)
---@return boolean
function M:Add(func)
	assert(func and type(func) == "function", "func is not a function")
	if  self.listenerSet[func] then
		return false
	end

	self.listenerSet[func] = true
	local v = { func, weak }
	setmetatable(v, weak)
	table.insert(self.listenerList, v)
	return true
end

---@param obj table
---@param method function(...:any)
---@return boolean
function M:AddObject(obj,method)
	assert(obj and type(obj) == "table", "obj is not a table")
	assert(method and type(method) == "function", "method is not a function")
	if  self.listenerSet[method] then
		return false
	end

	self.listenerSet[method] = true
	local v = { method, obj }
	table.insert(self.listenerList, v)
	return true
end

---@param func function(...:any)
---@return boolean
function M:Remove(func)
    assert(func and type(func) == "function", "func is not a function")
	if not self.listenerSet[func] then
		return false
    end
    self.listenerSet[func] = nil

	TableEx.ArrayRemove(self.listenerList, function(v)
		if v[1] == func then
			return true
		end
	end)
	
	return true
end

function M:RemoveAll()
	self.listenerSet = {}
    self.listenerList = {}
end

---@vararg any
---@return boolean
function M:Broadcast(...)
	if #self.listenerList == 0 then
        return false
    end
	
	for _,v in ipairs(self.listenerList) do
		if v[2] == weak then
			LuaHelper.XpCall(v[1], ...)
		else
			LuaHelper.XpCall(v[1], v[2], ...)
		end
	end
	return true
end

return M