---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 17:59
---

local TableEx = require("Utility.TableEx")
local LuaHelper = require("Utility.LuaHelper")
local Interface = require("Utility.Interface")

local weak = { __mode = "kv" }

---@class Observable
local M = Interface("Observable")

function M:__init()
	self.container = {}
end

---@param signal string
---@param func function(observer:table, ...:any)
---@param observer table
function M:Register(signal, func, observer)
	assert(signal and type(signal) == "string", "signal is not a string")
	assert(func and type(func) == "function", "func is not a function")
	local array = self.container[signal] or {}
	local obj = observer or weak
	local v = { func, obj }
	setmetatable(v, weak)
	array[#array+1] = v
	self.container[signal] = array
end

---@param signal string
---@param func function(observer:table, ...:any)
function M:Deregister(signal, func)
	assert(signal and type(signal) == "string", "signal is not a string")
	local container = self.container
	local array = container[signal]
	if not array then
		return
	end

	if not func then
		container[signal] = nil
		return
	end

	TableEx.ArrayRemove(array, function(v)
		if v[1] == func then
			return true
		end
	end)
end

---@param signal string
---@vararg any
function M:Notify(signal, ...)
	assert(signal and type(signal) == "string", "signal is not a string")
	local container = self.container
	local array = container[signal]
	if not array then
		return
	end

	for _, v in ipairs(array) do
		if v[2] == weak then
			LuaHelper.XpCall(v[1], ...)
		else
			LuaHelper.XpCall(v[1], v[2], ...)
		end
	end
end

return M
