---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 19:05
---

local lpbc = require "lpbc"

---@class ProtoDispatcher
local M = {}

local protoList = {}

---@param path string
function M.Init(path)
	lpbc.init(path)
end

function M.Cleanup()
	lpbc.cleanup()
end

---@param fileList string[]
function M.ImportProtoFile(fileList)
	for _, name in ipairs(fileList) do
		print("ImportProtoFile", name)
		assert(lpbc.import(name))
	end
end

---@param typename string
---@param target any
---@param func function(target:any, ...:any)
function M.AddDispatch(typename, target, func)
	local listener = protoList[typename]
	if not listener then
		listener = {}
		protoList[typename] = listener
	end
	if target then
		listener[target] = func
	else
		table.insert(listener, func)
	end
end

---@param typename string
function M.UnDispatch(typename)
	protoList[typename] = nil
end

---@param typename string
---@param target any
function M.RemoveDispatch(typename, target)
	local listener = protoList[typename]
	if listener then
		listener[target] = nil
	end
end

---@param typename string
---@vararg any
function M.DispatchMessage(typename, ...)
	local listener = protoList[typename]
	if listener then
		for target, func in pairs(listener) do
			func(target, ...)
		end
	end
end

return M