---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/2/25 17:31
---
local Interface = require "Utility.Interface"
local lfixed = require("lfixed")

---@class RandomGenerator
local M = Interface("RandomGenerator")

---@param seed integer
function M:__init(seed)
	self.seed = seed or os.time()
	if self.seed == 0 then
		self.seed = 1
	end
end

function M:Next()
	local x = self.seed
	x = x ~ (x << 13)
	x = x ~ (x >> 17)
	x = x ~ (x << 5)
	self.seed = x
	return x
end

function M:NextFixed()
	return lfixed.new(self:Next())
end

function M:NextFloat()
	return (self:Next() % 0x7FFFFFFF) / 0x7FFFFFFF
end

function M:NextRange(min, max)
	return min + self:Next() % (max - min + 1)
end

function M:NextRangeFixed(min, max)
	return min + self:NextFixed() * (max - min)
end

function M:NextRangeFloat(min, max)
	return min + self:NextFloat() * (max - min)
end

function M:Choice(array)
	if not array or #array == 0 then
		return nil
	end
	local index = self:NextRange(1, #array)
	return array[index]
end

return M