---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/14 16:44
---

---@class UEHelper
local M = {}

---@type GI_G01GameInstance_C
local gameInstance = nil

---@param gameInst GI_G01GameInstance_C
function M.Initialize(gameInst)
	gameInstance = gameInst
end

function M.Shutdown()
    gameInstance = nil
end

---@return GI_G01GameInstance_C
function M.GetGameInstance()
    return gameInstance
end

---@return UWorld
function M.GetWorld()
	return gameInstance:GetWorld()
end

---@param subsystemClass USubsystem
---@return USubsystem
function M.GetGameInstanceSubsystem(subsystemClass)
	return UE.USubsystemBlueprintLibrary.GetGameInstanceSubsystem(gameInstance, subsystemClass)
end

return M