---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/14 16:44
---

---@class UEHelper
local M = {}

---@type GI_G01GameInstance_C
local gameInstance = nil

function M.Initialize(gameInst)
	gameInstance = gameInst
end

function M.Shutdown()
    gameInstance = nil
end

function M.GetGameInstance()
    return gameInstance
end
function M.GetWorld()
	return gameInstance:GetWorld()
end

return M