
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/2/28
---

local LuaHelper = require("Utility.LuaHelper")
local Buff = require("GamePlay.Combat.GameLogic.Buffer")
local Fix = require("lfixed")

---@class HealBuffer
local M = LuaHelper.LuaClass(Buff)

function M:__OnNew(buffData)
    -- 调用基类构造函数
    M.Super.__OnNew(self,buffData)
    
	local param = buffData.param.split(",")
    -- 治疗Buff特有属性 只是一个例子
    self.healValue = Fix.new(param[0] or 0)
    self.healPercent = Fix.new(param[1] or 0)
end

--- 应用治疗效果
---@param target CombatEntity 目标实体
function M:ApplyEffect(target)
    if not target:IsAlive() then
        return
    end
    
    -- 计算治疗量
    local healAmount = Fix.new(0)
    
    -- 固定治疗值
    healAmount = healAmount + self.healValue
    
    -- 百分比治疗（基于最大HP）
    if self.healPercent:ToNumber() > 0 then
        local percentHeal = target.prop.maxHp * self.healPercent
        healAmount = healAmount + percentHeal
    end
    
    -- 应用层数加成
    if self.stackCount > 1 then
        healAmount = healAmount * Fix.new(self.stackCount)
    end
    
    -- 执行治疗
    target:Heal(healAmount)
    
    print("[HealBuffer] Applied heal:", healAmount:ToNumber(), "to", target.name)
end

return M