---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/3/4
---

local LuaHelper = require("Utility.LuaHelper")
local CombatActor = require("GamePlay.Combat.GameView.CombatActor")
local CombatSystem = require("GamePlay.Combat.GameLogic.CombatSystem")
local CombatEvent = require("GamePlay.Combat.GameLogic.CombatEvent")
local M = LuaHelper.LuaClass()

function M:__OnNew(skillData)
		CombatEvent.Subscribe()
		self.combatSystem = CombatSystem:New(CombatEvent.EventType.CombatEntityCreate,function(entity) self:CombatEntityCreate(entity)  end)
		self.players = {}
	
end
-- 创建战斗实体
-- ---@param entity CombatEntity 战斗实体
function M:CombatEntityCreate(entity)
	local actor = CombatActor:New(entity)
	self.players[entity.id] = actor
end

return M