---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/19 11:38
---

---@type Log
local Log = require("Utility.Log")
local UEHelper = require( "Core.UEHelper")

local configs = {}
local preloadedWidgets = {}
local bIsPreloaded = false

---@class UIConfigSystem
local M = {}

---@param name string
---@param controllerPath string
---@param viewPath string
---@param bPreload boolean|nil
function M.Register(name, controllerPath, viewPath, bPreload)
	assert(name and type(name) == "string", "name must be string")
	assert(controllerPath and type(controllerPath) == "string", "controllerPath must be string")
	assert(viewPath and type(viewPath) == "string", "viewPath must be string")
	
	if configs[name] then
		return
	end
	
	local controllerClass = require(controllerPath)
	if not controllerClass then
        Log.Error("UIConfigSystem", "Failed to load controller class for: " .. name)
        return
    end
	
	configs[name] = {
		controllerClass = controllerClass,
 		viewPath = viewPath,
		bPreload = bPreload
    }
	if bIsPreloaded and bPreload then
		local subsystem = UEHelper.GetGameInstanceSubsystem(UE.UAssetSubsystem)
		subsystem:RequestAsyncLoadAsset(viewPath)
        preloadedWidgets[#preloadedWidgets + 1] = viewPath
    end
end

function M.Preload()
	if bIsPreloaded then
        return
    end
    local subsystem = UEHelper.GetGameInstanceSubsystem(UE.UAssetSubsystem)
    for _, config in pairs(configs) do
        if config.bPreload then
			subsystem:RequestAsyncLoadAsset(config.viewPath)
            preloadedWidgets[#preloadedWidgets + 1] = config.viewPath
        end
    end
	bIsPreloaded = true
end

function M.Unload()
	if not bIsPreloaded then
        return
    end
	bIsPreloaded = false
	
    local subsystem = UEHelper.GetGameInstanceSubsystem(UE.UAssetSubsystem)
    
    for i = 1, #preloadedWidgets do
        subsystem:ClearCachedAsset(preloadedWidgets[i])
    end
    preloadedWidgets = {}
end

function M.Destroy()
	M.Unload()
	preloadedWidgets = {}
	configs = {}
end

function M.Get(name)
    return configs[name]
end



return M