---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/26 18:38
---

local UEHelper = require("Core.UEHelper")

local M = {}

---@return UWidget
function M.CreateMaskUWidget()
	local viewClass = UE.UClass.Load("/Game/UI/Common/WBP_Mask.WBP_Mask_C")
	if not viewClass then
		return nil
	end
	return UE.UWidgetBlueprintLibrary.Create(UEHelper.GetWorld(),viewClass)
end

---@param widget UWidget
---@param bRecursive boolean
function M.DuplicateWidget(widget, bRecursive)
	if not widget then
		return nil
	end
	local widgetClass = widget:GetClass()
	if not widgetClass then
		return nil
	end

	local newWidget = UE.NewObject(widgetClass,widget:GetGameInstance())
	if not newWidget then
		return nil
	end

	if widget.WidgetStyle then
		newWidget.WidgetStyle = widget.WidgetStyle
	end

	newWidget:SetVisibility(widget:GetVisibility())

	newWidget:SetRenderOpacity(widget:GetRenderOpacity())

	if widget.GetToolTipText then
		newWidget:SetToolTipText(widget:GetToolTipText())
	end

	if widget.GetNavigation then
		newWidget:SetNavigation(widget:GetNavigation())
	end

	if widget.GetClipping then
		newWidget:SetClipping(widget:GetClipping())
	end

	if widget.GetText then
		local originalText = widget:GetText()
		if originalText then
			newWidget:SetText(originalText)
		end
	end

	if bRecursive then
		if widget.GetChildrenCount and widget.GetChildAt then
			local childCount = widget:GetChildrenCount()
			for i = 0, childCount - 1 do
				local child = widget:GetChildAt(i)
				if child then
					local newChild = M.DuplicateWidget(child, bRecursive)
					if newChild then
						newWidget:AddChild(newChild)
					end
				end
			end
		end
	end
	return newWidget
end

---@param widget UWidget
---@return FVector2D
function M.GetWidgetLocalSize(widget)
	if not widget then
		return nil
	end

	local geometry = widget:GetCachedGeometry()
	if not geometry then
		return nil
	end
	return UE.USlateBlueprintLibrary.GetLocalSize(geometry)
end

---@param widget UWidget
---@return FVector2D
function M.GetWidgetViewportPosition(widget)
	if not widget then
		return nil
	end

	local geometry = widget:GetCachedGeometry()
	if not geometry then
		return nil
	end

	local pixelPosition = UE.FVector2D(0,0)
	local viewportPosition = UE.FVector2D(0,0)
	UE.USlateBlueprintLibrary.LocalToViewport(widget:GetGameInstance(), geometry, UE.FVector2D(0,0),pixelPosition, viewportPosition)
	return viewportPosition
end

---@param widget UWidget
---@return USizeBox
function M.WrapWidgetInSizeBox(widget)
	if not widget then
		return nil
	end
	local sizeBox = UE.NewObject(UE.USizeBox,widget:GetGameInstance())
	if not sizeBox then
		return nil
	end

	local desiredSize = M.GetWidgetLocalSize(widget)
	sizeBox:SetWidthOverride(desiredSize.X)
	sizeBox:SetHeightOverride(desiredSize.Y)
	sizeBox:AddChild(widget)
	return sizeBox
end

---@param panel UPanelWidget
---@param widget UWidget
---@return UWidget
function M.DuplicateWidgetToPanel(panel, widget)
	if not panel or not widget then
		return nil
	end
	local position = M.GetWidgetViewportPosition(widget)
	local size = M.GetWidgetLocalSize(widget)
	local newWidget = M.DuplicateWidget(widget, true)
	local inSizeBox = M.WrapWidgetInSizeBox(newWidget)
	if inSizeBox then
		panel:AddChild(inSizeBox)
	end

	if inSizeBox.Slot then
		inSizeBox.Slot:SetSize(UE.FVector2D(size.X, size.Y))
		inSizeBox.Slot:SetPosition(position)
	end
	return newWidget
end

--- @param uiView UIViewBase
--- @param panel UPanelWidget
--- @param button UButton
function M.GuideToButton(uiView,panel,button,event)
	local maskWidget = M.CreateMaskUWidget()
	local slot = panel:AddChild(maskWidget)
	if panel:IsA(UE.UOverlay) then
		slot:SetHorizontalAlignment(UE.EHorizontalAlignment.HAlign_Fill)
		slot:SetVerticalAlignment(UE.EVerticalAlignment.VAlign_Fill)
	elseif panel:IsA(UE.UCanvasPanel) then
		local anchor = UE.FAnchors()
		anchor.Minimum = UE.FVector2D(0, 0)
		anchor.Maximum = UE.FVector2D(1, 1)
		slot:SetAnchors(anchor)
		local margin = UE.FMargin(0, 0, 0, 0)
		slot:SetOffsets(margin)
	end
	local newWidget = M.DuplicateWidgetToPanel(maskWidget.CanvasPanel, button)
	newWidget.OnClicked:Add(uiView, function()
		uiView:TriggerEvent(event)
		newWidget.OnClicked:Clear()
		maskWidget:RemoveFromParent()
	end)
end

return M