---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/17 14:23
---

local Observable = require("Core.Observable")

---@class UIViewBase
local M = UnLua.Class()

function M:Construct()
    self.subject = Observable()
end

function M:Destruct()
	if self.subject then
		self.subject:RemoveAll()
		self.subject = nil
	end
end

--- @param signal string
--- @param func function(...:any)
--- @param observer table @[optional]
function M:SubscribeEvent(signal, func, observer)
    self.subject:Register(signal, func, observer)
end

--- @param signal string
function M:UnsubscribeEvent(signal)
    self.subject:Deregister(signal)
end

--- @param signal string
function M:CreateEvent(signal)
	return function(...)
		self:TriggerEvent(signal, ...)
	end
end

function M:RemoveAllEvent()
	self.subject:RemoveAll()
end
--- @param signal string
--- @vararg any
function M:TriggerEvent(signal, ...)
    self.subject:Notify(signal, ...)
end

--- @param bIsVisible boolean
function M:SetVisible(bIsVisible)
    self:SetVisibility(bIsVisible and UE.ESlateVisibility.SelfHitTestInvisible or UE.ESlateVisibility.Collapsed)
end

--- @param name string
--- @return UWidget|nil
function M:GetChildWidget(name)
	return self[name]
end

--- @param name string
--- @param callback function
function M:BindOnClick(name, callback)
	local button = self[name]
	if button and button.OnClicked then
		button.OnClicked:Add(self, callback)
	end
end

--- @param name string
--- @param callback function
function M:BindOnTextChanged(name, callback)
	local textBlock = self[name]
	if textBlock and textBlock.OnTextChanged then
		textBlock.OnTextChanged:Add(self, callback)
	end
end

--- @param name string
--- @param text string|nil
function M:SetChildText(name, text)
	local textBlock = self[name]
	if textBlock then
		textBlock:SetText(text or "")
	end
end

--- @param name string
--- @return string
function M:GetChildText(name)
	local textBlock = self[name]
	if textBlock then
		return textBlock:GetText()
	end
	return ""
end

--- @param name string
--- @param enabled boolean
function M:SetChildEnabled(name, enabled)
	local widget = self[name]
	if widget then
		widget:SetIsEnabled(enabled)
	end
end

return M