---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanmingyu.smy.
--- DateTime: 2026/3/4 11:38
---

local CsvParser = require("Utility.CsvParser")

---@class CsvDatas
local M = {}

local BASE_PATH = "Config/DataTable/"

M.CardDefine = {}
M.CardLevelUpDefine = {}
M.CardAttributeDefine = {}
M.CardAttrLevelUpDefine = {}

local function LoadCardDefine()
	local csvData = CsvParser.Read(BASE_PATH .. "CardDefine.csv")
	local tb = {}
	if csvData then
		for i = 1, csvData:Count() do
			local data = {
				id = csvData:GetValue(i, "id"),
				name = csvData:GetValue(i, "name"),
				iconId = csvData:GetValue(i, "iconId"),
				attributeId = csvData:GetValue(i, "attributeId"),
				levelUpId = csvData:GetValue(i, "levelUpId"),
			}

			-- 以id作为 key，避免遍历
			tb[data.id] = data
		end
	end

	return tb
end

local function LoadCardLevelUpDefine()
	local csvData = CsvParser.Read(BASE_PATH .. "CardLevelUpDefine.csv")
	local tb = {}
	if csvData then
		for i = 1, csvData:Count() do
			local data = {
				id = csvData:GetValue(i, "id"),
				level = csvData:GetValue(i, "level"),
				exp = csvData:GetValue(i, "exp"),
				cost = csvData:GetValue(i, "cost"),
				attrLevelUpId = csvData:GetValue(i, "attrLevelUpId"),
			}

			tb[data.id] = data
		end
	end

	return tb
end

local function LoadCardAttributeDefine()
	local csvData = CsvParser.Read(BASE_PATH .. "CardAttributeDefine.csv")
	local tb = {}
	if csvData then
		for i = 1, csvData:Count() do
			local data = {
				id = csvData:GetValue(i, "id"),
				hp = csvData:GetValue(i, "hp"),
				atk = csvData:GetValue(i, "atk"),
				def = csvData:GetValue(i, "def"),
				crit = csvData:GetValue(i, "crit"),
				critDef = csvData:GetValue(i, "critDef"),
				critDamage = csvData:GetValue(i, "critDamage"),
				critDamageDef = csvData:GetValue(i, "critDamageDef"),
				miss = csvData:GetValue(i, "miss"),
				hitOdds = csvData:GetValue(i, "hitOdds"),
				spd = csvData:GetValue(i, "spd"),
				damageAmp = csvData:GetValue(i, "damageAmp"),
				damageRd = csvData:GetValue(i, "damageRd"),
				hpPercent = csvData:GetValue(i, "hpPercent"),
				atkPercent = csvData:GetValue(i, "atkPercent"),
				defPercent = csvData:GetValue(i, "defPercent"),
				skillInc = csvData:GetValue(i, "skillInc"),
				skillRd = csvData:GetValue(i, "skillRd"),
				breakInc = csvData:GetValue(i, "breakInc")
			}

			tb[data.id] = data
		end
	end

	return tb
end

local function LoadCardAttrLevelUpDefine()
	local csvData = CsvParser.Read(BASE_PATH .. "CardAttrLevelUpDefine.csv")
	local tb = {}
	if csvData then
		for i = 1, csvData:Count() do
			local data = {
				id = csvData:GetValue(i, "id"),
				hp = csvData:GetValue(i, "hp"),
				atk = csvData:GetValue(i, "atk"),
				def = csvData:GetValue(i, "def"),
				crit = csvData:GetValue(i, "crit"),
				critDef = csvData:GetValue(i, "critDef"),
				critDamage = csvData:GetValue(i, "critDamage"),
				critDamageDef = csvData:GetValue(i, "critDamageDef"),
				miss = csvData:GetValue(i, "miss"),
				hitOdds = csvData:GetValue(i, "hitOdds"),
				spd = csvData:GetValue(i, "spd"),
				damageAmp = csvData:GetValue(i, "damageAmp"),
				damageRd = csvData:GetValue(i, "damageRd"),
				hpPercent = csvData:GetValue(i, "hpPercent"),
				atkPercent = csvData:GetValue(i, "atkPercent"),
				defPercent = csvData:GetValue(i, "defPercent"),
				skillInc = csvData:GetValue(i, "skillInc"),
				skillRd = csvData:GetValue(i, "skillRd"),
				breakInc = csvData:GetValue(i, "breakInc")
			}

			tb[data.id] = data
		end
	end
	
	return tb
end

function M.Initialize()
	M.CardDefine = LoadCardDefine()
	M.CardLevelUpDefine = LoadCardLevelUpDefine()
	M.CardAttributeDefine = LoadCardAttributeDefine()
	M.CardAttrLevelUpDefine = LoadCardAttrLevelUpDefine()
end

function M.Deinitialize()
	M.CardDefine = nil
	M.CardLevelUpDefine = nil
	M.CardAttributeDefine = nil
	M.CardAttrLevelUpDefine = nil
end

return M