---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/17 17:21
---

local UEHelper = require("Core.UEHelper")

local layerConfig = { State = 200, Dialog = 201, Lock = 202, MsgBox = 203, Toast = 204, Top = 205 }
local layers = {}
local layersRef = {}

local function CreateLayer(name, zOrder)
	local layerClass
	if name == "Dialog" or name == "Top" then
		layerClass = UE.UCanvasPanel
    else
		layerClass = UE.UOverlay
    end
	
	local layer = UE.NewObject(layerClass,UEHelper.GetGameInstance())

	local slot = UE.FGameViewportWidgetSlot()
	slot.ZOrder = zOrder
	slot.bAutoRemoveOnWorldRemoved = false

	---@type UGameViewportSubsystem
	local subsystem = UE.USubsystemBlueprintLibrary.GetEngineSubsystem(UE.UGameViewportSubsystem)
	subsystem:AddWidget(layer, slot)
	layer:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
	layersRef[zOrder] = UnLua.Ref(layer)
	return layer
end

---@class UILayerSystem
local M = {}

function M.Start()
	for name, zOrder in pairs(layerConfig) do
        layers[name] = CreateLayer(name,zOrder)
    end
end

function M.Destroy()
	for _, layer in pairs(layers) do
        if layer then
			layer:RemoveFromParent()
			UnLua.Unref(layer)
        end
    end
	layersRef = {}
	layers = {}
end

---@param userWidget UUserWidget
---@param layerName string
function M.AddToLayer(userWidget, layerName)
    local layer = layers[layerName]
	if layer and userWidget then
		if layer:IsA(UE.UOverlay) then
			local slot = layer:AddChildToOverlay(userWidget)
			slot:SetHorizontalAlignment(UE.EHorizontalAlignment.HAlign_Fill)
			slot:SetVerticalAlignment(UE.EVerticalAlignment.VAlign_Fill)
		else
			local slot = layer:AddChildToCanvas(userWidget)
			local anchor = UE.FAnchors()
			anchor.Minimum = UE.FVector2D(0, 0)
			anchor.Maximum = UE.FVector2D(1, 1)
			slot:SetAnchors(anchor)
			local margin = UE.FMargin(0, 0, 0, 0)
			slot:SetOffsets(margin)
		end
    end
end

return M