---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujinchun.ljc
--- DateTime: 2026/3/4
---

local LuaHelper = require("Utility.LuaHelper")

local M = LuaHelper.LuaClass()

return M