---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:48
---

local lpeg = require("lpeg")

---@type lproject
local lproject = require("lproject")

---@class CsvParser
local M = {}

local P = lpeg.P
local S = lpeg.S
local C = lpeg.C
local Ct = lpeg.Ct
local Cs = lpeg.Cs

local eol = P'\r\n' + P'\n'
local quoted_field = '"' * Cs(((P(1) - '"') + P'""' / '"')^0) * '"'
local unquoted_field = C((1 - S',\r\n"')^0)
local field = quoted_field + unquoted_field
local record = Ct(field * (',' * field)^0)
local nonemptyrecord = #P(1 - eol) * record
local records = Ct((record * eol)^0 * nonemptyrecord^-1) * -1

local function CsvMatch(s)
	local success, result = pcall(lpeg.match, records, s)
	if not success then
		return nil
	end
	return result

end

--- 解析CSV字符串为结构化数据
--- @param s string 
--- @return table 
function M.Parse(s)
	assert(s and type(s) == "string", "s must be a string")
	
	local data = CsvMatch(s)
	if not data or #data < 3 then
		return nil
	end
	
	if #(data[1]) ~= #(data[2]) then
		return nil
	end

	---@class csvData
	local t = {}

	local fieldCount = #(data[1])

	t._property = {}

	for columnIndex = 1, fieldCount do
		local columnName = assert(data[1][columnIndex])
		t._property[columnName] = columnIndex
	end

	local lineCount = #data - 2

	for rowIndex = 1, lineCount do
		t[rowIndex] = {}
	end

	for columnIndex = 1, fieldCount do
		local dataType = data[2][columnIndex]
		
		if dataType == "uint" or dataType == "int" or dataType == "int32" or 
		   dataType == "int64" or dataType == "uint32" or dataType == "uint64" then
			for rowIndex = 1, lineCount do
				t[rowIndex][columnIndex] = math.tointeger(data[rowIndex + 2][columnIndex]) or 0
			end
		elseif dataType == "string" then
			for rowIndex = 1, lineCount do
				t[rowIndex][columnIndex] = data[rowIndex + 2][columnIndex] or ""
			end
		elseif dataType == "float" then
			for rowIndex = 1, lineCount do
				t[rowIndex][columnIndex] = tonumber(data[rowIndex + 2][columnIndex]) or 0
			end
		elseif dataType == "bool" then
			for rowIndex = 1, lineCount do
				t[rowIndex][columnIndex] = math.tointeger(data[rowIndex + 2][columnIndex]) or 0
			end
		end
	end

	--- @param lineNumber number
	--- @param property string
	--- @return string | table | number | integer
	function t:GetValue(lineNumber, property)
		if not lineNumber or not property then
			error("GetValue: lineNumber and property are required")
		end
		
		local columnIndex = self._property[property]
		if not columnIndex then
			error("GetValue: property '" .. property .. "' not found")
		end
		
		local row = self[lineNumber]
		if not row then
			error("GetValue: line number " .. lineNumber .. " out of range")
		end
		
		return row[columnIndex]
	end

	--- @param lineNumber number
	--- @return table
	function t:GetRow(lineNumber)
		if not lineNumber then
			error("GetRow: lineNumber is required")
		end
		return self[lineNumber]
	end

	---
	--- @return integer
	function t:Count()
		return #self
	end
	return t
end

---
--- 从文件读取CSV数据
--- @param filename string
--- @return table
function M.Read(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	local pathFile = lproject.get_content_dir() .. filename
	
	local file = UE.File()
	if not file:Open(pathFile, "rb") then
		return nil
	end

	local s = file:Read(file:TotalSize())
	file:Close()
	
	if not s then
		return nil
	end
	
	local testBom = string.sub(s, 1, 3)
	local bom = string.char(0xEF, 0xBB, 0xBF)
	if testBom == bom then
		s = string.sub(s, 4)
	end
	
	return M.Parse(s)
end

return M