---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:48
---

local lpeg = require("lpeg")

---@type lproject
local lproject = require("lproject")

---@class CsvParser
local M = {}

local P = lpeg.P
local S = lpeg.S
local C = lpeg.C
local Ct = lpeg.Ct
local Cs = lpeg.Cs

local eol = P'\r\n' + P'\n'
local quoted_field = '"' * Cs(((P(1) - '"') + P'""' / '"')^0) * '"'
local unquoted_field = C((1 - S',\r\n"')^0)
local field = quoted_field + unquoted_field
local record = Ct(field * (',' * field)^0)
local nonemptyrecord = #P(1 - eol) * record
local records = Ct((record * eol)^0 * nonemptyrecord^-1) * -1

local function csv_parse(s)
	assert(type(s) == 'string', 'bad argument #1 (expected string)')
	return lpeg.match(records, s)
end

---@param s string
---@return table
function M.Parse(s)
	local data = csv_parse(s)
	if #(data[1]) ~= #(data[2]) then
		return nil
	end

	---@class csvData
	local t = {}

	local fieldCount = #(data[1])

	t._proptery ={}

	for i = 1,fieldCount do
		local name = assert(data[1][i])
		t._proptery[name] = i
	end

	local lineCount = #data -2

	for i = 1, lineCount do
		t[i] = {}
	end

	for j = 1,fieldCount do
		local _type = data[2][j]
		if _type == "uint" or _type == "int" or _type == "int32" or _type == "int64" or _type == "uint32" or _type == "uint64" then
			for i = 1, lineCount do
				t[i][j] = math.tointeger(data[i+2][j]) or 0
			end
		elseif _type == "string" then
			for i = 1, lineCount do
				t[i][j] = data[i+2][j] or ""
			end
		elseif _type == "float" then
			for i = 1, lineCount do
				t[i][j] = tonumber(data[i+2][j]) or 0
			end
		elseif _type == "bool" then
			for i = 1, lineCount do
				t[i][j] = math.tointeger(data[i+2][j]) or 0
			end
		end
	end

	---@param lineNumber number
	---@param proptery string
	---@return string | table | number | integer
	function t:GetValue(lineNumber, proptery)
		local nIndex = assert(self._proptery[proptery])
		local row = self[lineNumber]
		assert(row)
		return row[nIndex]
	end

	---@param lineNumber number
	---@return table
	function t:GetRow(lineNumber)
		return self[lineNumber]
	end

	---@return integer
	function t:Count()
		return #self
	end
	return t
end

---@param filename string
---@return table
function M.Read(filename)
	local path = lproject.get_content_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"rb") then
		return nil
	end

	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	local testBom = string.sub(s, 1,3)
	local bom = string.char(0xEF, 0xBB, 0xBF)
	if testBom == bom then
		s = string.sub(s,4)
	end
	return M.Parse(s)
end

return M