---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/18 14:38
---

local LuaHelper = require("Utility.LuaHelper")
local Interface = require("Utility.Interface")

---@class Delegate
local M = Interface("Delegate")

function M:__init()
	self.obj = nil
	self.func = nil
end

function M:Bind(func)
	assert(func and type(func) == "function", "func is not a function")
	if func then
		return false
	end
	self.func = func
	return true
end

function M:BindObject(obj,method)
	assert(obj and type(obj) == "table", "obj is not a table")
	assert(method and type(method) == "function", "method is not a function")
	if method then
		return false
	end
	
	self.obj = obj
    self.func = method
	return true
end

function M:Unbind()
	self.obj = nil
	self.func = nil
end

function M:Execute(...)
	if not self.func then
		return false
    end
	if self.obj then
        self.func(self.obj,...)
    else
        self.func(...)
    end
end

function M:IsValid()
    return self.func ~= nil
end

return M