---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 18:54
---

---@type lproject
local lproject = require("lproject")

----@type ltw2_core
local lcore = require("ltw2.core")

----@type ltw2_event
local levent = require("ltw2.event")

local LuaHelper = require("Utility.luaHelper")

local function ReceiveBeginPlay()
	assert(levent.start(1), "levent.start failed")
end

local tickerList = {}

local function Tick(deltaTime)
	levent.run()
	for obj, func in pairs(tickerList) do
		LuaHelper.XpCall(func, obj, deltaTime * 1000)
	end
end

local function ReceiveEndPlay()
	levent.stop()
end

lproject.set_beginplay_callback(ReceiveBeginPlay)

lproject.set_tick_callback(Tick)

lproject.set_endplay_callback(ReceiveEndPlay)

---@class Eventloop
local M = {}

---@return boolean
function M.Startup()
	return lproject.startup()
end

function M.Shutdown()
	return lproject.shutdown()
end
---@param obj any
---@param func function
function M.AddTicker(obj, func)
	tickerList[obj] = func
end

---@param obj any
function M.DelTicker(obj)
	tickerList[obj] = nil
end

function M.ResetTicker()
	tickerList = {}
end

---@return integer
function M.ClockMonotonic()
	return lcore.clock_monotonic()
end

---@return integer
function M.ClockRealtime()
	return lcore.clock_realtime()
end

---@param duration integer
function M.SleepFor(duration)
	lcore.sleep_for(duration)
end

---@param intervalMs integer
---@param func function
---@return ltw2_event_timer_watcher
function M.Timeout(intervalMs, func, bLoop)
	local timerWatcher = levent.timer_watcher_new()
	return timerWatcher:start(intervalMs, not bLoop, func) and timerWatcher
end

return M