---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 18:46
---

local LuaHelper = require "Utility.LuaHelper"

---@class HistoryManager
local M = LuaHelper.LuaClass()

function M:__OnNew(maxStep)
	self.undoStack = {}
	self.redoStack = {}
	self.maxStep = maxStep or 256
end

function M:AddHistory(his)
	assert(his.Undo and his.Redo)
	table.insert(self.undoStack, his)
	if #self.undoStack > self.maxStep then
		table.remove(self.undoStack, 1)
	end
	self.redoStack = {}
end

function M:Undo()
	local his = table.remove(self.undoStack)
	if his then
		his:Undo()
		table.insert(self.redoStack, his)
	end
end

function M:Redo()
	local his = table.remove(self.redoStack)
	if his then
		his:Redo()
		table.insert(self.undoStack, his)
	end
end

function M:Clear()
    self.undoStack = {}
    self.redoStack = {}
end

function M:IsCanUndo()
	return #self.undoStack > 0
end
function M:IsCanRedo()
	return #self.redoStack > 0
end

return M