---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:45
---

local lpeg = require("lpeg")

---@type lproject
local lproject = require("lproject")

lpeg.locale(lpeg)

---@class IniParser
local M = {}

local grammar = nil

M.config = function(config)
	local separatorChar = config.separator or '=' 
	local commentChars = config.comment or ';#' 
	local shouldTrim = config.trim == nil and true or config.trim
	local lowerCaseKeys = config.lowercase == nil and false or config.lowercase
	local useEscape = config.escape == nil and true or config.escape

	-- LPeg shortcut
	local P = lpeg.P    -- Pattern
	local R = lpeg.R    -- Range
	local S = lpeg.S    -- String
	local V = lpeg.V    -- Variable
	local C = lpeg.C    -- Capture
	local Cf = lpeg.Cf  -- Capture floding
	local Cc = lpeg.Cc  -- Constant capture
	local Ct = lpeg.Ct  -- Table capture
	local Cg = lpeg.Cg  -- Group capture
	local Cs = lpeg.Cs  -- Capture String (replace)
	local space = lpeg.space -- include tab and new line (\n)
	local alpha = lpeg.alpha
	local digit = lpeg.digit
	local any = P(1)

	local underscoreOrAlpha = P('_') + alpha 
	local keyIdentifier = underscoreOrAlpha^1 * (underscoreOrAlpha + digit)^0
	
	if useEscape then
		any = any
			- P'\\a' + P'\\a'/'\a' -- bell
			- P'\\n' + P'\\n'/'\n' -- newline
			- P'\\r' + P'\\r'/'\r' -- carriage return
			- P'\\t' + P'\\t'/'\t' -- horizontal tab
			- P'\\f' + P'\\f'/'\f' -- form feed
			- P'\\b' + P'\\b'/'\b' -- back space
			- P'\\v' + P'\\v'/'\v' -- vertical tab
			- P'\\\\' + P'\\\\'/'\\' -- backslash
	end

	grammar = P{
		'all';
		key = not lowerCaseKeys and C(keyIdentifier) * space^0 or Cs(keyIdentifier / function(s) return s:lower() end) * space^0,
		sep = P(separatorChar),
		cr = P'\n' + P'\r\n',
		comment = S(commentChars)^1 * lpeg.print^0,
		string = space^0 * P'"' * Cs((any - P'"' + P'""'/'"')^0) * P'"' * space^0,
		value = shouldTrim and space^0 * C(((space - '\n')^0 * (any - space)^1)^1) * space^0 or C((any - P'\n') ^1),
		set = Cg(V'key' * V'sep' * (V'string' + V'value')),
		line = space^0 * (V'comment' + V'set'),
		body = Cf(Ct'' * (V'cr' + V'line')^0, rawset),
		label = P'[' * space^0 * V'key' * space^0 * P']' * space^0,
		section = space^0 * Cg(V'label' * V'body'),
		sections = V'section' * (V'cr' + V'section')^0,
		all = Cf(Ct'' * ((V'cr' + V'line')^0 * V'sections'^0), rawset) * (V'cr' + -1),
	}
end

--- 解析INI格式字符串
--- @param s string
--- @return table
function M.Parse(s)
	assert(s and type(s) == "string", "s must be a string")
	
	local success, result = pcall(lpeg.match, grammar, s)
	if not success then
		return nil
	end
	return result
end

---
--- 从文件读取并解析INI数据
--- @param filename string
--- @return table
function M.Read(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	
	local pathFile = lproject.get_content_dir() .. filename
	local file = UE.File()
	if not file:Open(pathFile,"rb") then
		return nil
	end
	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	if not s then
		return nil	
	end
	
	local success, result = pcall(lpeg.match, grammar, s)
	if not success then
		return nil
	end
	return result
end

M.config({})

return M