---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:56
---

local interface = {}

function interface.__index(self, key)
	local metatable = getmetatable(self)
	local value = metatable[key]
	self[key] = value
	return value
end

function interface.__pairs()
	error("cannot use pairs")
end

function interface.__ipairs()
	error("cannot use ipairs")
end

local mt = {}

function mt:__call(...)
	local obj = setmetatable({}, self)
	local init = obj.__init
	if init then
		local success, result = pcall(init, obj, ...)
		if success then
			obj = result or obj
		else
			error("Interface initialization failed: " .. tostring(result))
		end
	end
	return obj
end

function mt:__newindex(key, value)
	if value == nil then
		return
	end
	local keys = self._keys
	keys[#keys + 1] = key
	return rawset(self, key, value)
end

return function()
	local obj = {}
	obj.__index = interface.__index
	obj.__pairs = interface.__pairs
	obj.__ipairs = interface.__ipairs
	obj._keys = {}
	return setmetatable(obj, mt)
end