---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:56
---

local interface = {}

function interface.__index(self,k)
	local mt = getmetatable(self)
	local v = mt[k]
	self[k] = v
	return v
end

function interface.__pairs()
	error("cannot use pairs")
end

function interface.__ipairs()
	error("cannot use ipairs")
end

local mt = {}

function mt:__call(...)
	local obj = setmetatable({}, self)
	local init = obj.__init
	if init then
		obj = init(obj,...) or obj
	end
	return obj
end

function mt:__newindex(k, v)
	if v == nil then
		return
	end
	local keys = self._keys
	keys[#keys + 1] = k
	return rawset(self, k, v)
end

return function()
	local obj = {}
	obj.__index = interface.__index
	obj.__pairs = interface.__pairs
	obj.__ipairs = interface.__ipairs
	obj._keys = {}
	return setmetatable(obj, mt)
end