---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:40
---

---@type ljson
local ljson = require("ljson")

---@type lproject
local lproject = require("lproject")

---@class Json
local M = {}

---@param filename string
---@return string | table | number | integer | boolean
function M.Read(filename)
	local path = lproject.get_app_sandboxes_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"rb") then
		return nil
	end
	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	return ljson.decode(s)
end

---@param filename string
---@param jsonData table
---@return string | table | number | integer | boolean
function M.Write(filename,jsonData)
	local s = ljson.encode(jsonData)
	local path = lproject.get_app_sandboxes_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"wb") then
		return nil
	end
	local r = file:Write(s)
	file:Close()
	return r
end

---@param filename string
---@return string | table | number | integer | boolean
function M.ReadToContent(filename)
	local path = lproject.get_content_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"rb") then
		return nil
	end
	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	return ljson.decode(s)
end

---@param filename string
---@param jsonData table
---@return string | table | number | integer | boolean
function M.WriteToContent(filename,jsonData)
	local s = ljson.encode(jsonData)
	local path = lproject.get_content_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"wb") then
		return nil
	end
	local r = file:Write(s)
	file:Close()
	return r
end

return M