---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:40
---

---@type ljson
local ljson = require("ljson")

---@type lproject
local lproject = require("lproject")

local function Read(filePath)
	local file = UE.File()
	if not file:Open(filePath,"rb") then
		return nil
	end

	local s = file:Read(file:TotalSize())
	file:Close()
	
	if not s then
        return nil
    end

	local success, jsonData = pcall(ljson.decode, s)
	if not success then
		return nil
	end
	return jsonData
end

local function Write(filePath, jsonData)
	local success, s = pcall(ljson.encode, jsonData)
	if not success or not s then
		return false
	end
	local file = UE.File()
	if not file:Open(filePath, "wb") then
		return false
	end

	success = file:Write(s);
	file:Close()
	return success
end

---@class JsonFile
local M = {}

--- 从内容目录读取JSON文件
--- @param filename string
--- @return string | table | number | integer | boolean
function M.Read(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_content_dir() .. filename
	return Read(filePath)
end

--- 向内容目录写入JSON文件
--- @param filename string
--- @param jsonData table
--- @return boolean
function M.Write(filename, jsonData)
	assert(filename and type(filename) == "string", "filename must be a string")
	assert(jsonData and type(jsonData) == "table", "jsonData must be a table")
	
	local filePath = lproject.get_content_dir() .. filename
	return Write(filePath, jsonData)
end

--- 从沙盒目录读取JSON文件
--- @param filename string
--- @return string | table | number | integer | boolean
function M.ReadFromSandbox(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_app_sandboxes_dir() .. filename
	return Read(filePath)
end

--- 向沙盒目录写入JSON文件
--- @param filename string
--- @param jsonData table
--- @return boolean
function M.WriteToSandbox(filename, jsonData)
	assert(filename and type(filename) == "string", "filename must be a string")
	assert(jsonData and type(jsonData) == "table", "jsonData must be a table")
	local filePath = lproject.get_app_sandboxes_dir() .. filename
	return Write(filePath, jsonData)
end

return M