---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 19:05
---

local print = print

local dump = {}

local maxDepth = 64

local function pushString(s)
	dump[#dump+1] = s
end

local function subTable(t,d)
	d = d + 1
	local s = string.rep("\t",d)
	if d <= maxDepth then
		for k,v in pairs(t) do
			if type(v) == "table" then
				pushString(string.format("%s[%s]={",s,k))
				subTable(v,l)
				pushString(string.format("%s}",s))
			elseif type(v) == "string" then
				pushString(string.format('%s[%s]="%s"',s,k,v))
			else
				pushString(string.format("%s[%s]=%s",s,k,tostring(v)))
			end
		end
	else
		pushString(string.format("%s__level_limit",s))
	end
end

local function pushTable(t)
	pushString(string.format("[%s]={",tostring(t)))
	subTable(t,0)
	pushString("}")
end

local debug_getinfo = debug.getinfo
local string_format = string.format

---@class Log
local M = {}

---@param d integer depth
function M.Config(d)
	if d then
		assert(math.type(l) == "integer")
		maxDepth = d
	end
end

local function ToString(...)
	local t = { ... }
	for _,v in ipairs(t) do
		if type(v) == "table" then
			pushTable(v)
		else
			pushString(tostring(v))
		end
	end
	local s = table.concat(dump,"\n")
	dump = {}
	return s
end

function M.Error(...)
	local s = ToString(...)
	local info = debug_getinfo(2,"Sl")
	UnLua.LogError(string_format("%s file[%s] line[%d]",s,info.source, info.currentline))
end

function M.Warning(...)
	local s = ToString(...)
	local info = debug_getinfo(2,"Sl")
	UnLua.LogWarn(string_format("%s file[%s] line[%d]",s,info.source, info.currentline))
end

function M.Info(...)
	local s = ToString(...)
	local info = debug_getinfo(2,"Sl")
	UnLua.Log(string_format("%s file[%s] line[%d]",s,info.source, info.currentline))
end

function M.PrintT(t)
	local print_r_cache = {}
	local function sub_print_r(t, indent)
		if (print_r_cache[tostring(t)]) then
			print(indent .. "*" .. tostring(t))
		else
			print_r_cache[tostring(t)] = true
			if (type(t) == "table") then
				for pos, val in pairs(t) do
					if (type(val) == "table") then
						print(indent .. "[" .. pos .. "] => " .. tostring(t) .. " {")
						sub_print_r(val, indent .. string.rep(" ", string.len(pos) + 8))
						print(indent .. string.rep(" ", string.len(pos) + 6) .. "}")
					elseif (type(val) == "string") then
						print(indent .. "[" .. pos .. '] => "' .. val .. '"')
					else
						print(indent .. "[" .. pos .. "] => " .. tostring(val))
					end
				end
			else
				print(indent .. tostring(t))
			end
		end
	end
	if (type(t) == "table") then
		print(tostring(t) .. " {")
		sub_print_r(t, "  ")
		print("}")
	else
		sub_print_r(t, "  ")
	end
	print()
end

function M.Printf(fmt, ...)
	print(string.format(tostring(fmt), ...))
end

return M
