---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 19:10
---

---@class LuaHelper
local M = {}

---@param func function
---@vararg any @[optional]
---@return any
function M.XpCall(func, ...)
	local ret
	if func then
		ret = table.pack(xpcall(func, function(err)
			print(err)
			print(debug.traceback())
		end, ...))

		return table.unpack(ret, 2)
	end
end

---@param super_name string @[optional]
---@vararg any @[optional]
---@return LuaClass
function M.LuaClass(super_name)
	local super_class = nil
	if super_name ~= nil then
		super_class = require(super_name)
	end

	local NotExist = {}
	local function Index(t, k)
		local mt = getmetatable(t)
		local super = mt
		while super do
			local v = rawget(super, k)
			if v ~= nil and not rawequal(v, NotExist) then
				rawset(t, k, v)
				return v
			end
			super = rawget(super, "super")
		end

		local p = mt[k]
		if p ~= nil then
			if type(p) == "function" then
				rawset(t, k, p)
			elseif rawequal(p, NotExist) then
				return nil
			end
		else
			rawset(mt, k, NotExist)
		end

		return p
	end

	---@class LuaClass
	local new_class = {}
	new_class.__index = Index
	new_class.__gc = function(self)
		if not rawget(self, "__bInstance") then
			return
		end
		local mt = getmetatable(self)
		while mt do
			local func = rawget(mt, "__OnGC")
			if func then
				M.XpCall(func, self)
			end
			mt = rawget(mt, "super")
		end
	end
	new_class.super = super_class

	---@generic T
	---@param self T
	---@return T
	function new_class.New(self, ...)
		local o = {
			__bInstance = true
		}
		setmetatable(o, self)
		M.XpCall(self.__OnNew, o, ...)
		return o
	end
	return new_class
end

---@generic T
---@param obj T
---@param method fun(obj:T, ...:any) T
---@return fun(...:any) T
function M.Handler(obj, method)
	return function(...)
		return method(obj, ...)
	end
end

---@param target any
---@param func fun(target:any, ...:any)
---@vararg any @[optional]
function M.HandleFunc(target, func, ...)
	local param = table.pack(...)
	return function(...)
		local finalParam = {}
		for k, v in ipairs(param) do
			table.insert(finalParam, v)
		end
		for k, v in ipairs(table.pack(...)) do
			table.insert(finalParam, v)
		end
		func(target, table.unpack(finalParam))
	end
end

---分割
---@param str string
---@param delimiter string
---@return table
function M.Split(str, delimiter)
	if str == nil or str == '' or delimiter == nil then
		return {}
	end
	local result = {}
	for match in (str .. delimiter):gmatch("(.-)" .. delimiter) do
		table.insert(result, match)
	end
	return result
end

---通用日期格式化
---@param format string yyyy.MM.dd hh:mm:ss
---@param time number 时间戳秒 
function M.DateFormat(format, time)
	local date = os.date("*t", time)
	local o = {
		['(M+)'] = tostring(date.month), -- 月份
		['(d+)'] = tostring(date.day), -- 日
		['(h+)'] = tostring(date.hour), -- 小时
		['(m+)'] = tostring(date.min), -- 分
		['(s+)'] = tostring(date.sec), -- 秒
		['(q+)'] = tostring(math.floor((date.month + 2) / 3)), -- 季度
	}

	local yS, yE, str = string.find(format, "(y+)")
	if yS then
		local len = yE - yS + 1
		format = string.gsub(format, str, string.sub(tostring(date.year), 5 - len), 1)
	end
	for k, v in pairs(o) do
		local yS, yE, str = string.find(format, k)
		if (yS) then
			local len = yE - yS + 1
			local reply = len == 1 and v or string.sub("0" .. v, string.len(v))
			format = string.gsub(format, str, reply, 1)
		end
	end
	return format
end

---时间格式化
---@param format string hh:mm:ss
---@param seconds number 时间数秒 
function M.SecondsFormat(format, seconds)
	local sign = seconds >= 0 and "" or "-"
	seconds = math.abs(seconds)
	local o = {
		'(h+)', -- 小时
		'(m+)', -- 分
		'(s+)' -- 秒
	}
	local scale = {
		3600, 60, 1
	}

	for k, v in ipairs(o) do
		local yS, yE, str = string.find(format, v)
		if (yS) then
			local len = yE - yS + 1
			local value = math.floor(seconds / scale[k])
			seconds = seconds - value * scale[k]
			local reply = len == 1 and value or string.sub("0" .. value, string.len(value))
			format = string.gsub(format, str, reply, 1)
		end
	end

	return sign .. format
end

function M.DisableGlobalVariable()
	local __g = _G
	M.__exports = {}
	setmetatable(M.__exports, {
		__newindex = function(_, name, value)
			rawset(__g, name, value)
		end,

		__index = function(_, name)
			return rawget(__g, name)
		end
	})

	setmetatable(__g, {
		__newindex = function(_, name, value)
			error(string.format("Please use LuaHelper.__exports.%s to set global variable ", name), 0)
        end
	})
end

return M