---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 17:58
---

---@type lmsgpack
local lmsgpack = require("lmsgpack")

---@type lproject
local lproject = require("lproject")

local function Read(filePath)
	local file = UE.File()
	if not file:Open(filePath, "rb") then
		return nil
	end
	local s = file:Read(file:TotalSize())
	file:Close()
	if not s then
        return nil    
    end
	local success, msgpackData = pcall(lmsgpack.decode, s)
	if not success then
		return nil
	end
	return msgpackData
end

local function Write(filePath, ...)
	local success, s = pcall(lmsgpack.encode, ...)
	if not success or not s then
		return false
	end

	local file = UE.File()
	if not file:Open(filePath,"wb") then
		return false
	end

	success = file:Write(s)
	file:Close()
	return success
end

---@class MsgPackFile
local M = {}

--- 从内容目录读取MsgPack文件
---@param filename string
---@return any
function M.Read(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_content_dir() .. filename
	return Read(filePath)
end

--- 向内容目录写入MsgPack文件
--- @param filename string
--- @vararg string | table | number | integer | boolean
--- @return boolean
function M.Write(filename, ...)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_content_dir() .. filename
	return Write(filePath, ...)
end

--- 从沙盒目录读取MsgPack文件
--- @param filename string
--- @return any
function M.ReadFromSandbox(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_app_sandboxes_dir() .. filename
	return Read(filePath)
end

--- 向沙盒目录写入MsgPack文件
--- @param filename string
--- @vararg string | table | number | integer | boolean
--- @return boolean
function M.WriteToSandbox(filename, ...)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_app_sandboxes_dir() .. filename
	return Write(filePath, ...)
end

return M