---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 17:58
---

---@type lmsgpack
local lmsgpack = require("lmsgpack")

---@type lproject
local lproject = require("lproject")

---@class Msgpack
local M = {}

---@param filename string
---@return any
function M.Read(filename)
	local path = lproject.get_app_sandboxes_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"rb") then
		return nil
	end
	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	return lmsgpack.decode(s)
end

---@param filename string
---@vararg string | table | number | integer | boolean
---@return any
function M.Write(filename,...)
	local s = lmsgpack.encode(...)
	local path = lproject.get_app_sandboxes_dir().. filename
	local file = UE.File()
	if not file:Open(path,"wb") then
		return nil
	end
	local r = file:Write(s)
	file:Close()
	return r
end

return M