---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/17 17:59
---

local TableEx = require("Utility.TableEx")
local LuaHelper = require("Utility.LuaHelper")
local Interface = require("Utility.Interface")

local weak = { __mode = "kv" }

---@class Observable
local M = Interface("Observable")

function M:__init()
	self.container = {}
end

---@param signal string
---@param observer any
---@param func fun(observer:any, ...:any)
function M:Register(signal, observer, func)
	local list = self.container[signal] or {}
	local obj = observer or weak
	local v = { func, obj }
	setmetatable(v, weak)
	table.insert(list, v)
	self.container[signal] = list
end

---@param signal string
---@param observer any
function M:Deregister(signal, observer)
	local container = self.container
	local list = container[signal]
	if not list then
		return
	end

	if not observer then
		container[signal] = nil
		return
	end

	TableEx.ArrayRemoveItem(list, function(v)
		if v[2] == observer then
			return true
		end
	end)
end

---@param signal string
---@vararg any
function M:Notify(signal, ...)
	local container = self.container
	local list = container[signal]
	if not list then
		return
	end

	for _, v in ipairs(list) do
		if v[2] == weak then
			LuaHelper.XpCall(v[1], ...)
		else
			LuaHelper.XpCall(v[1], v[2], ...)
		end
	end
end

return M
