---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 19:14
---

---@class TableEx
local M = {}

-- 检查并确保输入为表，如果不是则返回空表
---@param t table
---@return table
function M.CheckTable(t)
	if type(t) ~= "table" then 
		return {} 
	end
	return t
end

-- 深拷贝一个表
---@param t table
---@return table
function M.DeepCopy(t)
	local copy = {}
	for key, value in pairs(t) do
		if type(value) == "table" then
			copy[key] = M.DeepCopy(value)
		else
			copy[key] = value
		end
	end
	return copy
end

-- 获取表的长度（键的数量）
---@param t table
---@return integer
function M.Length(t)
	local count = 0
	for _ in pairs(t) do
		count = count + 1
	end
	return count
end

-- 获取表的所有键
---@param t table
---@return table
function M.GetKeys(t)
    local keys = {}
    for key, _ in pairs(t) do
		keys[#keys + 1] = key
    end
    return keys
end

-- 获取表的所有值
---@param t table
---@return table
function M.GetValues(t)
	local values = {} 
	for _, value in pairs(t) do
		values[#values + 1] = value
	end
	return values
end

-- 合并两个表
---@param dest table
---@param src table
function M.Merge(dest, src)
	for key, value in pairs(src) do
		dest[key] = value
	end
end

-- 对表中的每个元素应用函数，并更新原表
---@param t table
---@param func function(v:any,k:any)
function M.Map(t, func)
	for key, value in pairs(t) do
		t[key] = func(value, key)
	end
end

-- 根据条件过滤表中的元素
---@param t table
---@param func function(v:any,k:any):boolean
function M.Filter(t, func)
	for key, value in pairs(t) do
		if func(value, key) then
			t[key] = nil
		end
	end
end

-- 遍历表并对每个元素执行指定函数
---@param t table
---@param func function(v:any,k:any)
function M.Foreach(t, func)
	for key, value in pairs(t) do
		func(value, key)
	end
end

-- 查找表中特定值对应的键
---@param t table
---@param value any
function M.KeyOf(t, value)
	for key, val in pairs(t) do
		if val == value then
			return key
		end
	end
	return nil
end

-- 根据条件筛选表中的元素
---@param t table
---@param func function(v:any,k:any):boolean
---@param isAll boolean
function M.GetFilter(t, func, isAll)
	if not isAll then
        for key, value in pairs(t) do
            if func(value, key) then
                return value, key
            end
        end
    end
	local result = {}
	local keys = {}
	for key, value in pairs(t) do
        if func(value, key) then
			result[#result + 1] = value
			keys[#keys + 1] = key
        end
    end
	return result, keys
end

-- 根据条件筛选数组中的元素
---@param array table
---@param func function(v:any):boolean
---@param isAll boolean
function M.GetFilterArray(array, func, isAll)
	if not isAll then
		for index, value in ipairs(array) do
			if func(value) then
				return value, index
			end
		end
	end

	local result = {}
	local indices = {}
	for index, value in ipairs(array) do
		if func(value) then
			result[#result + 1] = value
			indices[#indices + 1] = index
		end
	end
	return result, indices
end

-- 移除数组中满足条件的所有元素
---@param array table
---@param func function(v:T):boolean
function M.ArrayRemove(array, func)
	local length = #array
	local readIndex = 1
	local writeIndex = 1
	while readIndex <= length do
		local value = array[readIndex]
		array[readIndex] = nil
		if not func(value) then
			array[writeIndex] = value
			writeIndex = writeIndex + 1
		end
		readIndex = readIndex + 1
	end
end

-- 移除数组中的指定元素
---@param array table
---@param item any
---@return boolean true 如果移除成功，false 如果元素不存在
function M.ArrayRemoveItem(array, item)
    for index, v in ipairs(array) do
        if v == item then
            table.remove(array, index)
            return true
        end
    end
	return false
end

-- 遍历数组并对每个元素执行指定函数
---@param array table
---@param func function(v:any,k:integer)
function M.ArrayForeach(array, func)
	for index, value in ipairs(array) do
		func(value,index)
	end
end

-- 返回数组中的下一个元素，循环使用
---@param array table
---@param index integer
---@return any
function M.ArrayNext(array, index)
	if index >= #array then
		index = 1
	else
		index = index + 1
	end
	return array[index]
end

-- 在数组中查找特定值的位置
---@param array table
---@param item any
---@param begin integer
---@return integer
function M.ArrayIndexOf(array, item, begin)
	for index = begin or 1, #array do
		if array[index] == item then
			return index 
		end
	end
	return nil
end

--- 转换为数组（从栈顶到栈底）
---@param stack table
---@return table 数组
function M.StackToArray(stack)
    local result = {}
    for i = #stack, 1, -1 do
        result[#result + 1] = stack[i]
    end
    return result
end

-- 遍历堆栈中的所有元素（从栈顶到栈底）
---@param stack table
---@param func function(v:T)
function M.StackForeach(stack, func)
	for i = #stack, 1, -1 do
		func(stack[i])
	end
end

--- 将堆栈中的指定元素移动到顶部
---@param stack table
---@param item any
---@return boolean true 如果移动成功，false 如果元素不存在
function M.StackMoveToTop(stack, item)
    for i = #stack, 1, -1 do
        if stack[i] == item then
            table.remove(stack, i)
			stack[#stack + 1] = item
            return true
        end
    end
    return false
end

--- 弹出堆栈顶部的元素
---@param stack table
---@return any|nil 弹出的元素，如果堆栈为空则返回 nil
function M.StackPop(stack)
    if #stack == 0 then
        return nil
    end
	local count = #stack
	local item = stack[count]
	stack[count] = nil
    return item
end

--- 查看堆栈顶部的元素（不弹出）
---@param stack table
---@return any|nil 堆栈顶部的元素，如果堆栈为空则返回 nil
function M.StackPeek(stack)
    if #stack == 0 then
        return nil
    end
    return stack[#stack]
end

--- 压入元素到堆栈顶部
---@param stack table
---@param item any 要压入的元素
function M.StackPush(stack, item)
	stack[#stack + 1] = item
end

-- 移除堆栈中的指定元素
---@param stack table
---@param item any
---@return boolean true 如果移除成功，false 如果元素不存在
function M.StackRemoveItem(stack, item)
	for i = #stack, 1, -1 do
        if stack[i] == item then
            table.remove(stack, i)
            return true
        end
    end
    return false
end

return M