---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 19:14
---

---@class TableEx
local M = {}

---@param t table
---@return table
function M.CheckTable(t)
	if type(t) ~= "table" then 
		t = {} 
	end
	return t
end

---表深度拷贝
---@param t table
---@return table
function M.DeepCopy(t)
	local t2 = {}
	for k, v in pairs(t) do
		if type(v) == "table" then
			t2[k] = M.DeepCopy(v)
		else
			t2[k] = v
		end
	end
	return t2
end

---表长度
---@param t table
---@return inteter
function M.Length(t)
	local count = 0
	for _ in pairs(t) do
		count = count + 1
	end
	return count
end

---@param t table
---@return table
function M.GetKeys(t)
    local keys = {}
    for k, _ in pairs(t) do
		keys[#keys + 1] = k
    end
    return keys
end

---@param map table
---@return table
function M.GetMapValues(map)
	local values = {} 
	for _, v in pairs(map) do
		values[#values + 1] = v
	end
	return values
end

---@param dest table
---@param src table
function M.Merge(dest, src)
	for k, v in pairs(src) do
		dest[k] = v
	end
end

---@param t table
---@param func fun(v:any,k:any)
function M.Map(t, func)
	for k, v in pairs(t) do
		t[k] = func(v, k)
	end
end

---@param t table
---@param func fun(v:any,k:any)
function M.Walk(t, func)
	for k, v in pairs(t) do
		func(v,k)
	end
end

---@param t table
---@param func fun(v:any,k:any):boolean
function M.Filter(t, func)
	for k, v in pairs(t) do
		if func(v,k) then
			t[k] = nil
		end
	end
end

---@generic T
---@param array T[]
---@param func fun(v:T):boolean
function M.ArrayRemoveValue(array, func)
	assert(array and func)

	local l = #array
	local i = 1
	local j = 1
	while i <= l do
		local v = array[i]
		array[i] = nil
		if not func(v) then
			array[j] = v
			j = j + 1
		end
		i = i + 1
	end
end

---@generic T
---@param array T[]
---@param func fun(v:T,k:integer):boolean
function M.ArrayForeach(array, func)
	for k, v in ipairs(array) do
		func(v,k)
	end
end

---@generic T
---@param array T[]
---@retrun T 
function M.ArrayNext(array, index)
	if index >= #array then
		index = 1
	else
		index = index + 1
	end

	return array[index]
end

return M
