---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 17:51
---

---@type lxml
local lxml = require("lxml")

---@type lproject
local lproject = require("lproject")

---@class XmlParse
local M = {}

---@param s string
---@return table
function M.Parse(s)
	assert(type(s) == "string")
	return lxml.parse(s)
end

---@param filename string
---@return table
function M.Read(filename)
	local path = lproject.get_content_dir() .. filename
	local file = UE.File()
	if not file:Open(path,"rb") then
		return nil
	end
	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	return lxml.parse(s)
end

return M