---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 17:51
---

---@type lxml
local lxml = require("lxml")

---@type lproject
local lproject = require("lproject")

---@class XmlParser
local M = {}

---
--- 解析XML字符串
--- @param s string
--- @return table
function M.Parse(s)
	assert(s and type(s) == "string", "xmlString must be a string")
	local success, parsedData = pcall(lxml.parse, s)
	if not success then
		return nil
	end
	return parsedData
end

---
--- 从文件读取并解析XML
--- @param filename string
--- @return table
function M.Read(filename)
	assert(filename and type(filename) == "string", "filename must be a string")
	local filePath = lproject.get_content_dir() .. filename

	local file = UE.File()
	if not file:Open(filePath, "rb") then
		return nil
	end

	local s = UE.File.Read(file,file:TotalSize())
	file:Close()
	if not s then
		return nil
	end

	local success, parsedData = pcall(lxml.parse,s)
	if not success then
		return nil
	end
	return parsedData
end

return M