---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/24 10:14
---

---@type HttpObject
local M = UnLua.Class()

---@param target table
---@param func function
---@vararg any
function M:RegisterCompleteCallback(func)
	if func then
		self.responseCallback = func
	end
end

function M:UnRegisterCompleteCallback()
    self.responseCallback = nil
end

function M:OnCompleted(result, code)
	if not self.responseCallback then
        return
    end
	self.responseCallback(result, code)
end

return M 