---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/20 11:14
---
local LuaHelper = require("Utility.LuaHelper")
local UIManager = require("UI.UIManager")

---@class MsgBoxController : UIControllerBase
local M = LuaHelper.LuaClass("UI.UIControllerBase")

function M:__OnNew(name, view, model, title, content, type)
	self.Super.__OnNew(self, name, view, model)
	self.view:InitMessageBox(title,content,type)
	self.view:SubscribeEvent("OnCloseClick", self.OnCloseClick, self)
	self.view:SubscribeEvent("OnConfirmClick", self.OnConfirmClick, self)
	self.view:SubscribeEvent("OnCancelClick", self.OnCancelClick, self)
end

function M:SetConfirmCallback(confirmCallback)
	self.confirmCallback = confirmCallback
end

function M:SetCancelCallback(cancelCallback)
    self.cancelCallback = cancelCallback
end

function M:SetCloseCallback(closeCallback)
    self.closeCallback = closeCallback
end

function M:SetConfirmText(confirmText)
    self.view:SetChildText("TextBlock_Confirm", confirmText)
end

function M:SetCancelText(cancelText)
	self.view:SetChildText("TextBlock_Cancel", cancelText)
end

function M:OnCloseClick()
	if self.closeCallback then
		self.closeCallback()
	else
		UIManager.MsgBox_Close(self.name)
	end
end

function M:OnConfirmClick()
	if self.confirmCallback then
        self.confirmCallback()
	else
        UIManager.MsgBox_Close(self.name)
    end
end

function M:OnCancelClick()
	if self.cancelCallback then
		self.cancelCallback()
	else
		UIManager.MsgBox_Close(self.name)
	end
end

return M