---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2026/1/20 11:17
---

local ALERT_STYLE<const> = 1
local CONFIRM_STYLE<const> = 2

---@class WBP_MessageBox_C : UIViewBase
local M = UnLua.Class( "UI.UIViewBase")

function M:Construct()
	self.Super.Construct(self)
	if self.Button_Close then
		self.Button_Close.OnClicked:Add(self,self:CreateEvent("OnCloseClick"))
	end
	if self.Button_Confirm then
        self.Button_Confirm.OnClicked:Add(self, self:CreateEvent("OnConfirmClick"))
    end
	if self.Button_Cancel then
        self.Button_Cancel.OnClicked:Add(self, self:CreateEvent("OnCancelClick"))
    end
end

function M:InitMessageBox(title, content, type)
	if self.TextBlock_Title then
		if title then
			self.TextBlock_Title:SetText(title)
		else
			self.TextBlock_Title:SetText("")
		end
	end

	if self.TextBlock_Content then
		if content then
			self.TextBlock_Content:SetText(content)
		else
			self.TextBlock_Content:SetText("")
		end
	end

	if type == CONFIRM_STYLE then
		if self.Button_Confirm then
			self.Button_Confirm:SetVisibility(UE.ESlateVisibility.Visible)
		end
		if self.Button_Cancel then
			self.Button_Cancel:SetVisibility(UE.ESlateVisibility.Visible)
		end
	elseif type == ALERT_STYLE then
		if self.Button_Confirm then
			self.Button_Confirm:SetVisibility(UE.ESlateVisibility.Visible)
		end
		if self.Button_Cancel then
			self.Button_Cancel:SetVisibility(UE.ESlateVisibility.Collapsed)
		end
	end
end

return M
