---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hebo.pb.
--- DateTime: 2025/12/15 18:55
---

local IniParser = require "Utility.IniParser"

local config = IniParser.Read("Config/LuaDebugger.ini")
local dbg
UEPrint(config)
if config and config["Editor"] then
	if config["Editor"].bEnableDebug == "True" then
		package.cpath = package.cpath .. ';' .. config["Editor"].riderPluginsPath
		dbg = require('emmy_core')
		UEPrint(dbg)
		if dbg then
			dbg.tcpListen('localhost', 9966)
			if config["Editor"].bEnableWaitIDE == "True" then
				dbg.waitIDE()
			end
		else
			UEPrint("Deubgger not found")
		end
	end
end